{{ if .Values.certificate.enabled -}}

apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ template "kube-arangodb.operatorName" . }}-ca
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  secretName: {{ template "kube-arangodb.operatorName" . }}-ca
  duration: {{ .Values.certificate.ca.duration }}
  issuerRef:
    name: {{ template "kube-arangodb.operatorName" . }}-ca
  commonName: {{ .Values.certificate.ca.commonName }}
  isCA: true

{{- end }}