{{ if .Values.operator.features.storage -}}

apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: arangolocalstorages.storage.arangodb.com
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
spec:
    group: storage.arangodb.com
    names:
        kind: ArangoLocalStorage
        listKind: ArangoLocalStorageList
        plural: arangolocalstorages
        shortNames:
            - arangostorage
        singular: arangolocalstorage
    scope: Cluster
    versions:
        - name: v1alpha
          served: true
          storage: true
          schema:
              openAPIV3Schema:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true

{{- end }}