{{ .Deployment.FilterStart }}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Deployment.OperatorDeploymentName }}
  namespace: {{ .Deployment.Operator.Namespace }}
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        name: {{ .Deployment.OperatorDeploymentName }}
        app: arango-deployment-operator
    spec:
      serviceAccountName: {{ .Deployment.Operator.ServiceAccountName }}
      containers:
      - name: operator
        imagePullPolicy: {{ .ImagePullPolicy }}
        image: {{ .Image }}
        args:
          - --operator.deployment
          - --chaos.allowed={{ .Deployment.AllowChaos }}
        env:
        - name: MY_POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
        - name: MY_POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        ports:
        - name: metrics
          containerPort: 8528
        livenessProbe:
          httpGet:
            path: /health
            port: 8528
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready/deployment
            port: 8528
            scheme: HTTPS
          initialDelaySeconds: 5
          periodSeconds: 10
      tolerations:
      - key: "node.kubernetes.io/unreachable"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5
      - key: "node.kubernetes.io/not-ready"
        operator: "Exists"
        effect: "NoExecute"
        tolerationSeconds: 5

{{ .Deployment.FilterEnd }}
