run:
  issues-exit-code: 3
  timeout: 30m
  skip-dirs:
    - vendor
    - .gobuild
    - deps
    - tools
linters:
  disable-all: true
  enable:
    - gosimple
    - govet
    - ineffassign
    - staticcheck
    - typecheck
    - unconvert
    - unparam
    - unused
    - importas
    - gci
linters-settings:
  importas:
    no-unaliased: true
    alias:
      - alias: pbImplAuthenticationV1
        pkg: github.com/arangodb/kube-arangodb/integrations/authentication/v1
      - alias: pbAuthenticationV1
        pkg: github.com/arangodb/kube-arangodb/integrations/authentication/v1/definition
      - alias: pbImplAuthorizationV0
        pkg: github.com/arangodb/kube-arangodb/integrations/authorization/v0
      - alias: pbAuthorizationV0
        pkg: github.com/arangodb/kube-arangodb/integrations/authorization/v0/definition
      - alias: pbImplConfigV1
        pkg: github.com/arangodb/kube-arangodb/integrations/config/v1
      - alias: pbConfigV1
        pkg: github.com/arangodb/kube-arangodb/integrations/config/v1/definition
      - alias: pbImplEnvoyAuthV3
        pkg: github.com/arangodb/kube-arangodb/integrations/envoy/auth/v3
      - pkg: github.com/arangodb/kube-arangodb/integrations/pong/v1
        alias: pbImplPongV1
      - pkg: github.com/arangodb/kube-arangodb/integrations/pong/v1/definition
        alias: pbPongV1
      - alias: pbImplSchedulerV1
        pkg: github.com/arangodb/kube-arangodb/integrations/scheduler/v1
      - alias: pbSchedulerV1
        pkg: github.com/arangodb/kube-arangodb/integrations/scheduler/v1/definition
      - alias: pbImplSharedV1
        pkg: github.com/arangodb/kube-arangodb/integrations/shared/v1
      - alias: pbSharedV1
        pkg: github.com/arangodb/kube-arangodb/integrations/shared/v1/definition
      - alias: pbImplShutdownV1
        pkg: github.com/arangodb/kube-arangodb/integrations/shutdown/v1
      - alias: pbShutdownV1
        pkg: github.com/arangodb/kube-arangodb/integrations/shutdown/v1/definition
      - alias: pbImplStorageV2
        pkg: github.com/arangodb/kube-arangodb/integrations/storage/v2
      - alias: pbImplStorageV2Shared
        pkg: github.com/arangodb/kube-arangodb/integrations/storage/v2/shared
      - alias: pbImplStorageV2SharedS3
        pkg: github.com/arangodb/kube-arangodb/integrations/storage/v2/shared/s3
      - alias: pbStorageV2
        pkg: github.com/arangodb/kube-arangodb/integrations/storage/v2/definition
      - alias: analyticsApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/analytics/v1alpha1
      - alias: mlApiv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/ml/v1alpha1
      - alias: mlApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/ml/v1beta1
      - alias: networkingApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/networking/v1alpha1
      - alias: platformApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/platform/v1alpha1
      - alias: schedulerApiv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1alpha1
      - alias: schedulerContainerApiv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1alpha1/container
      - alias: schedulerContainerResourcesApiv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1alpha1/container/resources
      - alias: schedulerPodApiv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1alpha1/pod
      - alias: schedulerPodResourcesApiv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1alpha1/pod/resources
      - alias: schedulerProfilesv1alpha1
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1alpha1/profiles
      - alias: schedulerApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1
      - alias: schedulerContainerApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/container
      - alias: schedulerContainerResourcesApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/container/resources
      - alias: schedulerIntegrationApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/integration
      - alias: schedulerPolicyApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/policy
      - alias: schedulerPodApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/pod
      - alias: schedulerPodResourcesApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/pod/resources
      - alias: schedulerProfiles
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/scheduler/v1beta1/profiles
      - alias: shared
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/shared
      - alias: sharedApi
        pkg: github.com/arangodb/kube-arangodb/pkg/apis/shared/v1
      - alias: sharedReconcile
        pkg: github.com/arangodb/kube-arangodb/pkg/deployment/reconcile/shared
      - alias: analyticsShared
        pkg: github.com/arangodb/kube-arangodb/pkg/handlers/enterprise/analytics/shared
      - alias: mlShared
        pkg: github.com/arangodb/kube-arangodb/pkg/handlers/enterprise/ml/shared
      - alias: mlSharedTests
        pkg: github.com/arangodb/kube-arangodb/pkg/handlers/enterprise/ml/shared/test
      - alias: enterpriseShared
        pkg: github.com/arangodb/kube-arangodb/pkg/handlers/enterprise/shared
      - alias: kresources
        pkg: github.com/arangodb/kube-arangodb/pkg/util/k8sutil/resources
      - alias: ktls
        pkg: github.com/arangodb/kube-arangodb/pkg/util/k8sutil/tls
      - alias: pbEnvoyAuthV3
        pkg: github.com/envoyproxy/go-control-plane/envoy/service/auth/v3
      - alias: apps
        pkg: k8s.io/api/apps/v1
      - alias: batch
        pkg: k8s.io/api/batch/v1
      - alias: core
        pkg: k8s.io/api/core/v1
      - alias: policy
        pkg: k8s.io/api/policy/v1
      - alias: storage
        pkg: k8s.io/api/storage/v1
      - alias: meta
        pkg: k8s.io/apimachinery/pkg/apis/meta/v1
      - alias: typedCore
        pkg: k8s.io/client-go/kubernetes/typed/core/v1
      - alias: ugrpc
        pkg: github.com/arangodb/kube-arangodb/pkg/util/grpc
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/arangodb)
      - prefix(github.com/arangodb/kube-arangodb)
