---

run:
  issues-exit-code: 3
  timeout: 30m
  skip-dirs:
    - vendor
    - .gobuild
    - deps
    - tools

linters:
  disable-all: true
  enable:
    - deadcode
    - gosimple 
    - govet 
    - ineffassign 
    - staticcheck 
    - structcheck 
    - typecheck 
    - unconvert 
    - unparam 
    - unused 
    - varcheck
    - importas
    - gci

linters-settings:
  importas:
    no-unaliased: true
    alias:
      - pkg: k8s.io/api/core/v1
        alias: core
      - pkg: k8s.io/apimachinery/pkg/apis/meta/v1
        alias: meta
      - pkg: k8s.io/client-go/kubernetes/typed/core/v1
        alias: typedCore
      - pkg: k8s.io/api/apps/v1
        alias: apps
      - pkg: k8s.io/api/batch/v1
        alias: batch
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/arangodb)
      - prefix(github.com/arangodb/kube-arangodb)
