FROM golang:1.12.9-alpine AS downloader

# git is required by 'go mod'
RUN apk add git

WORKDIR /app

COPY go.mod .
COPY go.sum .
# It is done only once unless go.mod has been changed
RUN go mod download

FROM downloader

COPY pkg /app/pkg
COPY dashboard /app/dashboard

ARG VERBOSE
RUN CGO_ENABLED=0 go test ${VERBOSE} \
   ./pkg/apis/... \
   ./pkg/backup/... \
   ./pkg/deployment/... \
   ./pkg/storage/... \
   ./pkg/util/...
