apiVersion: v1
kind: ServiceAccount
metadata:
    name: {{ template "kube-arangodb-test.releaseName" . }}
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb-test.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.imagePullSecrets }}
    - name: {{ . }}
{{- end }}
{{- end }}