//
// DISCLAIMER
//
// Copyright 2026 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: integrations/authorization/v1/definition/definition.proto

package definition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorizationV1_Evaluate_FullMethodName     = "/authorization.AuthorizationV1/Evaluate"
	AuthorizationV1_EvaluateMany_FullMethodName = "/authorization.AuthorizationV1/EvaluateMany"
)

// AuthorizationV1Client is the client API for AuthorizationV1 service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthorizationV1 Service implementation
type AuthorizationV1Client interface {
	// Evaluates single permission
	Evaluate(ctx context.Context, in *AuthorizationV1PermissionRequest, opts ...grpc.CallOption) (*AuthorizationV1PermissionResponse, error)
	// Evaluates multiple permission
	EvaluateMany(ctx context.Context, in *AuthorizationV1PermissionManyRequest, opts ...grpc.CallOption) (*AuthorizationV1PermissionManyResponse, error)
}

type authorizationV1Client struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationV1Client(cc grpc.ClientConnInterface) AuthorizationV1Client {
	return &authorizationV1Client{cc}
}

func (c *authorizationV1Client) Evaluate(ctx context.Context, in *AuthorizationV1PermissionRequest, opts ...grpc.CallOption) (*AuthorizationV1PermissionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationV1PermissionResponse)
	err := c.cc.Invoke(ctx, AuthorizationV1_Evaluate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationV1Client) EvaluateMany(ctx context.Context, in *AuthorizationV1PermissionManyRequest, opts ...grpc.CallOption) (*AuthorizationV1PermissionManyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationV1PermissionManyResponse)
	err := c.cc.Invoke(ctx, AuthorizationV1_EvaluateMany_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationV1Server is the server API for AuthorizationV1 service.
// All implementations must embed UnimplementedAuthorizationV1Server
// for forward compatibility.
//
// AuthorizationV1 Service implementation
type AuthorizationV1Server interface {
	// Evaluates single permission
	Evaluate(context.Context, *AuthorizationV1PermissionRequest) (*AuthorizationV1PermissionResponse, error)
	// Evaluates multiple permission
	EvaluateMany(context.Context, *AuthorizationV1PermissionManyRequest) (*AuthorizationV1PermissionManyResponse, error)
	mustEmbedUnimplementedAuthorizationV1Server()
}

// UnimplementedAuthorizationV1Server must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizationV1Server struct{}

func (UnimplementedAuthorizationV1Server) Evaluate(context.Context, *AuthorizationV1PermissionRequest) (*AuthorizationV1PermissionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Evaluate not implemented")
}
func (UnimplementedAuthorizationV1Server) EvaluateMany(context.Context, *AuthorizationV1PermissionManyRequest) (*AuthorizationV1PermissionManyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EvaluateMany not implemented")
}
func (UnimplementedAuthorizationV1Server) mustEmbedUnimplementedAuthorizationV1Server() {}
func (UnimplementedAuthorizationV1Server) testEmbeddedByValue()                         {}

// UnsafeAuthorizationV1Server may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationV1Server will
// result in compilation errors.
type UnsafeAuthorizationV1Server interface {
	mustEmbedUnimplementedAuthorizationV1Server()
}

func RegisterAuthorizationV1Server(s grpc.ServiceRegistrar, srv AuthorizationV1Server) {
	// If the following call pancis, it indicates UnimplementedAuthorizationV1Server was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorizationV1_ServiceDesc, srv)
}

func _AuthorizationV1_Evaluate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationV1PermissionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationV1Server).Evaluate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationV1_Evaluate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationV1Server).Evaluate(ctx, req.(*AuthorizationV1PermissionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationV1_EvaluateMany_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationV1PermissionManyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationV1Server).EvaluateMany(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationV1_EvaluateMany_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationV1Server).EvaluateMany(ctx, req.(*AuthorizationV1PermissionManyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationV1_ServiceDesc is the grpc.ServiceDesc for AuthorizationV1 service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationV1_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "authorization.AuthorizationV1",
	HandlerType: (*AuthorizationV1Server)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Evaluate",
			Handler:    _AuthorizationV1_Evaluate_Handler,
		},
		{
			MethodName: "EvaluateMany",
			Handler:    _AuthorizationV1_EvaluateMany_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "integrations/authorization/v1/definition/definition.proto",
}
