//
// DISCLAIMER
//
// Copyright 2025 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.0
// source: integrations/authorization/v1/definition/types.proto

package definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// AuthorizationV1Effect defines the Statement Effect
type AuthorizationV1Effect int32

const (
	// Deny definition
	AuthorizationV1Effect_Deny AuthorizationV1Effect = 0
	// Allow definition
	AuthorizationV1Effect_Allow AuthorizationV1Effect = 1
)

// Enum value maps for AuthorizationV1Effect.
var (
	AuthorizationV1Effect_name = map[int32]string{
		0: "Deny",
		1: "Allow",
	}
	AuthorizationV1Effect_value = map[string]int32{
		"Deny":  0,
		"Allow": 1,
	}
)

func (x AuthorizationV1Effect) Enum() *AuthorizationV1Effect {
	p := new(AuthorizationV1Effect)
	*p = x
	return p
}

func (x AuthorizationV1Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuthorizationV1Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_integrations_authorization_v1_definition_types_proto_enumTypes[0].Descriptor()
}

func (AuthorizationV1Effect) Type() protoreflect.EnumType {
	return &file_integrations_authorization_v1_definition_types_proto_enumTypes[0]
}

func (x AuthorizationV1Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuthorizationV1Effect.Descriptor instead.
func (AuthorizationV1Effect) EnumDescriptor() ([]byte, []int) {
	return file_integrations_authorization_v1_definition_types_proto_rawDescGZIP(), []int{0}
}

// AuthorizationV1Action defines the Action type
type AuthorizationV1Action struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// name of the Action
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// description of the Action
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// list of the Action SubActions
	SubActions []string `protobuf:"bytes,3,rep,name=sub_actions,json=subActions,proto3" json:"sub_actions,omitempty"`
}

func (x *AuthorizationV1Action) Reset() {
	*x = AuthorizationV1Action{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationV1Action) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationV1Action) ProtoMessage() {}

func (x *AuthorizationV1Action) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationV1Action.ProtoReflect.Descriptor instead.
func (*AuthorizationV1Action) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v1_definition_types_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizationV1Action) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorizationV1Action) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthorizationV1Action) GetSubActions() []string {
	if x != nil {
		return x.SubActions
	}
	return nil
}

// AuthorizationV1Statement defines the Policy Statement
type AuthorizationV1Statement struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Statement Description
	Description string `protobuf:"bytes,1,opt,name=description,proto3" json:"description,omitempty"`
	// Statement Effect
	Effect AuthorizationV1Effect `protobuf:"varint,2,opt,name=effect,proto3,enum=authorization.AuthorizationV1Effect" json:"effect,omitempty"`
	// List of the Statement Actions
	Actions []string `protobuf:"bytes,3,rep,name=actions,proto3" json:"actions,omitempty"`
	// List of the Statement Resources
	Resources []string `protobuf:"bytes,4,rep,name=resources,proto3" json:"resources,omitempty"`
}

func (x *AuthorizationV1Statement) Reset() {
	*x = AuthorizationV1Statement{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationV1Statement) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationV1Statement) ProtoMessage() {}

func (x *AuthorizationV1Statement) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationV1Statement.ProtoReflect.Descriptor instead.
func (*AuthorizationV1Statement) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v1_definition_types_proto_rawDescGZIP(), []int{1}
}

func (x *AuthorizationV1Statement) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthorizationV1Statement) GetEffect() AuthorizationV1Effect {
	if x != nil {
		return x.Effect
	}
	return AuthorizationV1Effect_Deny
}

func (x *AuthorizationV1Statement) GetActions() []string {
	if x != nil {
		return x.Actions
	}
	return nil
}

func (x *AuthorizationV1Statement) GetResources() []string {
	if x != nil {
		return x.Resources
	}
	return nil
}

// AuthorizationV1Policy defines the Policy
type AuthorizationV1Policy struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Policy Name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Policy Description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	// List of Policy statements
	Statements []*AuthorizationV1Statement `protobuf:"bytes,3,rep,name=statements,proto3" json:"statements,omitempty"`
}

func (x *AuthorizationV1Policy) Reset() {
	*x = AuthorizationV1Policy{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationV1Policy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationV1Policy) ProtoMessage() {}

func (x *AuthorizationV1Policy) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationV1Policy.ProtoReflect.Descriptor instead.
func (*AuthorizationV1Policy) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v1_definition_types_proto_rawDescGZIP(), []int{2}
}

func (x *AuthorizationV1Policy) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorizationV1Policy) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *AuthorizationV1Policy) GetStatements() []*AuthorizationV1Statement {
	if x != nil {
		return x.Statements
	}
	return nil
}

// AuthorizationV1Role defines the Role
type AuthorizationV1Role struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Role Name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Role Description
	Description string `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
}

func (x *AuthorizationV1Role) Reset() {
	*x = AuthorizationV1Role{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationV1Role) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationV1Role) ProtoMessage() {}

func (x *AuthorizationV1Role) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationV1Role.ProtoReflect.Descriptor instead.
func (*AuthorizationV1Role) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v1_definition_types_proto_rawDescGZIP(), []int{3}
}

func (x *AuthorizationV1Role) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuthorizationV1Role) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

// AuthorizationV1User defines the User
type AuthorizationV1User struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// User Name
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *AuthorizationV1User) Reset() {
	*x = AuthorizationV1User{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AuthorizationV1User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizationV1User) ProtoMessage() {}

func (x *AuthorizationV1User) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v1_definition_types_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizationV1User.ProtoReflect.Descriptor instead.
func (*AuthorizationV1User) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v1_definition_types_proto_rawDescGZIP(), []int{4}
}

func (x *AuthorizationV1User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_integrations_authorization_v1_definition_types_proto protoreflect.FileDescriptor

var file_integrations_authorization_v1_definition_types_proto_rawDesc = []byte{
	0x0a, 0x34, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x6e, 0x0a, 0x15, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1f, 0x0a, 0x0b, 0x73, 0x75, 0x62, 0x5f, 0x61, 0x63, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0a, 0x73, 0x75, 0x62, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0xb2, 0x01, 0x0a, 0x18, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72,
	0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x53, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70,
	0x74, 0x69, 0x6f, 0x6e, 0x12, 0x3c, 0x0a, 0x06, 0x65, 0x66, 0x66, 0x65, 0x63, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x56, 0x31, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x52, 0x06, 0x65, 0x66, 0x66, 0x65,
	0x63, 0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x03, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x07, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x12, 0x1c, 0x0a, 0x09,
	0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x09, 0x72, 0x65, 0x73, 0x6f, 0x75, 0x72, 0x63, 0x65, 0x73, 0x22, 0x96, 0x01, 0x0a, 0x15, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x50, 0x6f,
	0x6c, 0x69, 0x63, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x47, 0x0a, 0x0a, 0x73, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x27,
	0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x53, 0x74,
	0x61, 0x74, 0x65, 0x6d, 0x65, 0x6e, 0x74, 0x52, 0x0a, 0x73, 0x74, 0x61, 0x74, 0x65, 0x6d, 0x65,
	0x6e, 0x74, 0x73, 0x22, 0x4b, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x52, 0x6f, 0x6c, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e,
	0x22, 0x29, 0x0a, 0x13, 0x41, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x56, 0x31, 0x55, 0x73, 0x65, 0x72, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x2a, 0x2c, 0x0a, 0x15, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x31, 0x45, 0x66,
	0x66, 0x65, 0x63, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79, 0x10, 0x00, 0x12, 0x09,
	0x0a, 0x05, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x01, 0x42, 0x4c, 0x5a, 0x4a, 0x67, 0x69, 0x74,
	0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62,
	0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x69,
	0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68,
	0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x31, 0x2f, 0x64, 0x65, 0x66,
	0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_integrations_authorization_v1_definition_types_proto_rawDescOnce sync.Once
	file_integrations_authorization_v1_definition_types_proto_rawDescData = file_integrations_authorization_v1_definition_types_proto_rawDesc
)

func file_integrations_authorization_v1_definition_types_proto_rawDescGZIP() []byte {
	file_integrations_authorization_v1_definition_types_proto_rawDescOnce.Do(func() {
		file_integrations_authorization_v1_definition_types_proto_rawDescData = protoimpl.X.CompressGZIP(file_integrations_authorization_v1_definition_types_proto_rawDescData)
	})
	return file_integrations_authorization_v1_definition_types_proto_rawDescData
}

var file_integrations_authorization_v1_definition_types_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_integrations_authorization_v1_definition_types_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_integrations_authorization_v1_definition_types_proto_goTypes = []interface{}{
	(AuthorizationV1Effect)(0),       // 0: authorization.AuthorizationV1Effect
	(*AuthorizationV1Action)(nil),    // 1: authorization.AuthorizationV1Action
	(*AuthorizationV1Statement)(nil), // 2: authorization.AuthorizationV1Statement
	(*AuthorizationV1Policy)(nil),    // 3: authorization.AuthorizationV1Policy
	(*AuthorizationV1Role)(nil),      // 4: authorization.AuthorizationV1Role
	(*AuthorizationV1User)(nil),      // 5: authorization.AuthorizationV1User
}
var file_integrations_authorization_v1_definition_types_proto_depIdxs = []int32{
	0, // 0: authorization.AuthorizationV1Statement.effect:type_name -> authorization.AuthorizationV1Effect
	2, // 1: authorization.AuthorizationV1Policy.statements:type_name -> authorization.AuthorizationV1Statement
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_integrations_authorization_v1_definition_types_proto_init() }
func file_integrations_authorization_v1_definition_types_proto_init() {
	if File_integrations_authorization_v1_definition_types_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_integrations_authorization_v1_definition_types_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationV1Action); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_integrations_authorization_v1_definition_types_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationV1Statement); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_integrations_authorization_v1_definition_types_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationV1Policy); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_integrations_authorization_v1_definition_types_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationV1Role); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_integrations_authorization_v1_definition_types_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AuthorizationV1User); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_integrations_authorization_v1_definition_types_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_integrations_authorization_v1_definition_types_proto_goTypes,
		DependencyIndexes: file_integrations_authorization_v1_definition_types_proto_depIdxs,
		EnumInfos:         file_integrations_authorization_v1_definition_types_proto_enumTypes,
		MessageInfos:      file_integrations_authorization_v1_definition_types_proto_msgTypes,
	}.Build()
	File_integrations_authorization_v1_definition_types_proto = out.File
	file_integrations_authorization_v1_definition_types_proto_rawDesc = nil
	file_integrations_authorization_v1_definition_types_proto_goTypes = nil
	file_integrations_authorization_v1_definition_types_proto_depIdxs = nil
}
