//go:build !ignore_autogenerated
// +build !ignore_autogenerated

//
// DISCLAIMER
//
// Copyright 2026 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1alpha1

import (
	policy "github.com/arangodb/kube-arangodb/pkg/apis/permission/v1alpha1/policy"
	v1 "github.com/arangodb/kube-arangodb/pkg/apis/shared/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionBindingRef) DeepCopyInto(out *ArangoPermissionBindingRef) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionBindingRef.
func (in *ArangoPermissionBindingRef) DeepCopy() *ArangoPermissionBindingRef {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionBindingRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ArangoPermissionBindingRefList) DeepCopyInto(out *ArangoPermissionBindingRefList) {
	{
		in := &in
		*out = make(ArangoPermissionBindingRefList, len(*in))
		copy(*out, *in)
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionBindingRefList.
func (in ArangoPermissionBindingRefList) DeepCopy() ArangoPermissionBindingRefList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionBindingRefList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicy) DeepCopyInto(out *ArangoPermissionPolicy) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicy.
func (in *ArangoPermissionPolicy) DeepCopy() *ArangoPermissionPolicy {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicy)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionPolicy) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicyList) DeepCopyInto(out *ArangoPermissionPolicyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPermissionPolicy, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicyList.
func (in *ArangoPermissionPolicyList) DeepCopy() *ArangoPermissionPolicyList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionPolicyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicyRoleBinding) DeepCopyInto(out *ArangoPermissionPolicyRoleBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicyRoleBinding.
func (in *ArangoPermissionPolicyRoleBinding) DeepCopy() *ArangoPermissionPolicyRoleBinding {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicyRoleBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionPolicyRoleBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicyRoleBindingList) DeepCopyInto(out *ArangoPermissionPolicyRoleBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPermissionPolicyRoleBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicyRoleBindingList.
func (in *ArangoPermissionPolicyRoleBindingList) DeepCopy() *ArangoPermissionPolicyRoleBindingList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicyRoleBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionPolicyRoleBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicyRoleBindingSpec) DeepCopyInto(out *ArangoPermissionPolicyRoleBindingSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(ArangoPermissionBindingRef)
		**out = **in
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(ArangoPermissionBindingRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicyRoleBindingSpec.
func (in *ArangoPermissionPolicyRoleBindingSpec) DeepCopy() *ArangoPermissionPolicyRoleBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicyRoleBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicyRoleBindingStatus) DeepCopyInto(out *ArangoPermissionPolicyRoleBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicyRoleBindingStatus.
func (in *ArangoPermissionPolicyRoleBindingStatus) DeepCopy() *ArangoPermissionPolicyRoleBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicyRoleBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicySpec) DeepCopyInto(out *ArangoPermissionPolicySpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(policy.Policy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicySpec.
func (in *ArangoPermissionPolicySpec) DeepCopy() *ArangoPermissionPolicySpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionPolicyStatus) DeepCopyInto(out *ArangoPermissionPolicyStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionPolicyStatus.
func (in *ArangoPermissionPolicyStatus) DeepCopy() *ArangoPermissionPolicyStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionPolicyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRole) DeepCopyInto(out *ArangoPermissionRole) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRole.
func (in *ArangoPermissionRole) DeepCopy() *ArangoPermissionRole {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRole)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionRole) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleList) DeepCopyInto(out *ArangoPermissionRoleList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPermissionRole, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleList.
func (in *ArangoPermissionRoleList) DeepCopy() *ArangoPermissionRoleList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionRoleList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleSpec) DeepCopyInto(out *ArangoPermissionRoleSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleSpec.
func (in *ArangoPermissionRoleSpec) DeepCopy() *ArangoPermissionRoleSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleStatus) DeepCopyInto(out *ArangoPermissionRoleStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make(ArangoPermissionBindingRefList, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleStatus.
func (in *ArangoPermissionRoleStatus) DeepCopy() *ArangoPermissionRoleStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleUserBinding) DeepCopyInto(out *ArangoPermissionRoleUserBinding) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleUserBinding.
func (in *ArangoPermissionRoleUserBinding) DeepCopy() *ArangoPermissionRoleUserBinding {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleUserBinding)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionRoleUserBinding) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleUserBindingList) DeepCopyInto(out *ArangoPermissionRoleUserBindingList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPermissionRoleUserBinding, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleUserBindingList.
func (in *ArangoPermissionRoleUserBindingList) DeepCopy() *ArangoPermissionRoleUserBindingList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleUserBindingList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionRoleUserBindingList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleUserBindingSpec) DeepCopyInto(out *ArangoPermissionRoleUserBindingSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(ArangoPermissionBindingRef)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(policy.Policy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleUserBindingSpec.
func (in *ArangoPermissionRoleUserBindingSpec) DeepCopy() *ArangoPermissionRoleUserBindingSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleUserBindingSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionRoleUserBindingStatus) DeepCopyInto(out *ArangoPermissionRoleUserBindingStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.UserRoleBinding != nil {
		in, out := &in.UserRoleBinding, &out.UserRoleBinding
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionRoleUserBindingStatus.
func (in *ArangoPermissionRoleUserBindingStatus) DeepCopy() *ArangoPermissionRoleUserBindingStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionRoleUserBindingStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionScope) DeepCopyInto(out *ArangoPermissionScope) {
	*out = *in
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(policy.Policy)
		(*in).DeepCopyInto(*out)
	}
	if in.Ref != nil {
		in, out := &in.Ref, &out.Ref
		*out = new(ArangoPermissionBindingRef)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionScope.
func (in *ArangoPermissionScope) DeepCopy() *ArangoPermissionScope {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionScope)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionScopedBindingRef) DeepCopyInto(out *ArangoPermissionScopedBindingRef) {
	*out = *in
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(ArangoPermissionBindingRef)
		**out = **in
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(ArangoPermissionScope)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionScopedBindingRef.
func (in *ArangoPermissionScopedBindingRef) DeepCopy() *ArangoPermissionScopedBindingRef {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionScopedBindingRef)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ArangoPermissionScopedBindingRefList) DeepCopyInto(out *ArangoPermissionScopedBindingRefList) {
	{
		in := &in
		*out = make(ArangoPermissionScopedBindingRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionScopedBindingRefList.
func (in ArangoPermissionScopedBindingRefList) DeepCopy() ArangoPermissionScopedBindingRefList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionScopedBindingRefList)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionToken) DeepCopyInto(out *ArangoPermissionToken) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionToken.
func (in *ArangoPermissionToken) DeepCopy() *ArangoPermissionToken {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionToken)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionToken) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionTokenList) DeepCopyInto(out *ArangoPermissionTokenList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPermissionToken, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionTokenList.
func (in *ArangoPermissionTokenList) DeepCopy() *ArangoPermissionTokenList {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionTokenList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPermissionTokenList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionTokenSpec) DeepCopyInto(out *ArangoPermissionTokenSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make(ArangoPermissionScopedBindingRefList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.TTL != nil {
		in, out := &in.TTL, &out.TTL
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.Policy != nil {
		in, out := &in.Policy, &out.Policy
		*out = new(policy.Policy)
		(*in).DeepCopyInto(*out)
	}
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = new(policy.Policy)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionTokenSpec.
func (in *ArangoPermissionTokenSpec) DeepCopy() *ArangoPermissionTokenSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionTokenSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPermissionTokenStatus) DeepCopyInto(out *ArangoPermissionTokenStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.User != nil {
		in, out := &in.User, &out.User
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Role != nil {
		in, out := &in.Role, &out.Role
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make(v1.Objects, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.ManagedPolicy != nil {
		in, out := &in.ManagedPolicy, &out.ManagedPolicy
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Policies != nil {
		in, out := &in.Policies, &out.Policies
		*out = make(v1.Objects, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Secret != nil {
		in, out := &in.Secret, &out.Secret
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	in.Refresh.DeepCopyInto(&out.Refresh)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPermissionTokenStatus.
func (in *ArangoPermissionTokenStatus) DeepCopy() *ArangoPermissionTokenStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPermissionTokenStatus)
	in.DeepCopyInto(out)
	return out
}
