{{ if .Values.rbac.enabled -}}
{{ if .Values.operator.features.scheduler -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ template "kube-arangodb.rbac" . }}-scheduler
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
    - apiGroups:
        - "scheduler.arangodb.com"
      resources:
        - "arangoprofiles"
        - "arangoprofiles/status"
        - "arangoschedulerpods"
        - "arangoschedulerpods/status"
        - "arangoschedulerdeployments"
        - "arangoschedulerdeployments/status"
        - "arangoschedulerbatchjobs"
        - "arangoschedulerbatchjobs/status"
        - "arangoschedulercronjobs"
        - "arangoschedulercronjobs/status"
      verbs:
        - "*"
    - apiGroups:
        - ""
      resources:
        - "pods"
        - "pods/status"
      verbs:
        - "*"
    - apiGroups:
        - "apps"
      resources:
        - "deployments"
        - "deployments/status"
      verbs:
        - "*"
    - apiGroups:
        - "batch"
      resources:
        - "jobs"
        - "jobs/status"
        - "cronjobs"
        - "cronjobs/status"
      verbs:
        - "*"
    - apiGroups:
        - "database.arangodb.com"
      resources:
        - "arangodeployments"
      verbs:
        - "get"
        - "list"
        - "watch"
{{- end }}
{{- end }}