//
// DISCLAIMER
//
// Copyright 2026 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.0
// source: pkg/sidecar/services/authorization/types/effect.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Statement Effect
type Effect int32

const (
	// Deny definition
	Effect_Deny Effect = 0
	// Allow definition
	Effect_Allow Effect = 1
)

// Enum value maps for Effect.
var (
	Effect_name = map[int32]string{
		0: "Deny",
		1: "Allow",
	}
	Effect_value = map[string]int32{
		"Deny":  0,
		"Allow": 1,
	}
)

func (x Effect) Enum() *Effect {
	p := new(Effect)
	*p = x
	return p
}

func (x Effect) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Effect) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_sidecar_services_authorization_types_effect_proto_enumTypes[0].Descriptor()
}

func (Effect) Type() protoreflect.EnumType {
	return &file_pkg_sidecar_services_authorization_types_effect_proto_enumTypes[0]
}

func (x Effect) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Effect.Descriptor instead.
func (Effect) EnumDescriptor() ([]byte, []int) {
	return file_pkg_sidecar_services_authorization_types_effect_proto_rawDescGZIP(), []int{0}
}

var File_pkg_sidecar_services_authorization_types_effect_proto protoreflect.FileDescriptor

var file_pkg_sidecar_services_authorization_types_effect_proto_rawDesc = []byte{
	0x0a, 0x35, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2f, 0x73, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2f, 0x65, 0x66, 0x66, 0x65, 0x63,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x74, 0x79, 0x70, 0x65, 0x73, 0x2a, 0x1d,
	0x0a, 0x06, 0x45, 0x66, 0x66, 0x65, 0x63, 0x74, 0x12, 0x08, 0x0a, 0x04, 0x44, 0x65, 0x6e, 0x79,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x41, 0x6c, 0x6c, 0x6f, 0x77, 0x10, 0x01, 0x42, 0x4c, 0x5a,
	0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x61, 0x6e,
	0x67, 0x6f, 0x64, 0x62, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x61, 0x72, 0x61, 0x6e, 0x67, 0x6f,
	0x64, 0x62, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x73, 0x69, 0x64, 0x65, 0x63, 0x61, 0x72, 0x2f, 0x73,
	0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x73, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x74, 0x79, 0x70, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_pkg_sidecar_services_authorization_types_effect_proto_rawDescOnce sync.Once
	file_pkg_sidecar_services_authorization_types_effect_proto_rawDescData = file_pkg_sidecar_services_authorization_types_effect_proto_rawDesc
)

func file_pkg_sidecar_services_authorization_types_effect_proto_rawDescGZIP() []byte {
	file_pkg_sidecar_services_authorization_types_effect_proto_rawDescOnce.Do(func() {
		file_pkg_sidecar_services_authorization_types_effect_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_sidecar_services_authorization_types_effect_proto_rawDescData)
	})
	return file_pkg_sidecar_services_authorization_types_effect_proto_rawDescData
}

var file_pkg_sidecar_services_authorization_types_effect_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_sidecar_services_authorization_types_effect_proto_goTypes = []interface{}{
	(Effect)(0), // 0: types.Effect
}
var file_pkg_sidecar_services_authorization_types_effect_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_sidecar_services_authorization_types_effect_proto_init() }
func file_pkg_sidecar_services_authorization_types_effect_proto_init() {
	if File_pkg_sidecar_services_authorization_types_effect_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_sidecar_services_authorization_types_effect_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_pkg_sidecar_services_authorization_types_effect_proto_goTypes,
		DependencyIndexes: file_pkg_sidecar_services_authorization_types_effect_proto_depIdxs,
		EnumInfos:         file_pkg_sidecar_services_authorization_types_effect_proto_enumTypes,
	}.Build()
	File_pkg_sidecar_services_authorization_types_effect_proto = out.File
	file_pkg_sidecar_services_authorization_types_effect_proto_rawDesc = nil
	file_pkg_sidecar_services_authorization_types_effect_proto_goTypes = nil
	file_pkg_sidecar_services_authorization_types_effect_proto_depIdxs = nil
}
