{{ if eq .Values.operator.scope "legacy" -}}
# Scope "legacy" selected
{{ else if eq .Values.operator.scope "namespaced" -}}
# Scope "namespaced" selected
{{ if .Values.operator.features.storage -}}
{{ fail (printf "Storage Operator not supported in %s scope!" .Values.operator.scope) -}}
{{ end -}}
{{ else -}}
{{ fail (printf "Operator Scope %s is not supported!" .Values.operator.scope) -}}
{{ end -}}
apiVersion: apps/v1
kind: Deployment
metadata:
    name: {{ template "kube-arangodb.operatorName" . }}
    namespace: {{ .Release.Namespace }}
{{- if .Values.operator.annotations }}
    annotations:
{{ toYaml .Values.operator.annotations | indent 8 }}
{{- end }}
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
spec:
    replicas: {{ .Values.operator.replicaCount }}
    strategy:
{{ toYaml .Values.operator.updateStrategy | indent 8 }}
    selector:
        matchLabels:
            app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
            app.kubernetes.io/managed-by: {{ .Release.Service }}
            app.kubernetes.io/instance: {{ .Release.Name }}
            release: {{ .Release.Name }}
    template:
        metadata:
            labels:
                app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
                helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
                app.kubernetes.io/managed-by: {{ .Release.Service }}
                app.kubernetes.io/instance: {{ .Release.Name }}
                release: {{ .Release.Name }}
{{- if .Values.operator.annotations }}
            annotations:
{{ toYaml .Values.operator.annotations | indent 16 }}
{{- end }}
        spec:
{{- if .Values.serviceAccount.create }}
            serviceAccountName: {{ template "kube-arangodb.operatorName" . }}
{{- else if .Values.serviceAccount.name }}
            serviceAccountName: {{ .Values.serviceAccount.name }}
{{- end }}
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: beta.kubernetes.io/arch
                          operator: In
                          values:
                            - amd64
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      topologyKey: "kubernetes.io/hostname"
                      labelSelector:
                        matchExpressions:
                          - key: app.kubernetes.io/name
                            operator: In
                            values:
                              - {{ template "kube-arangodb.name" . }}
                          - key: app.kubernetes.io/instance
                            operator: In
                            values:
                              - {{ .Release.Name }}
            hostNetwork: false
            hostPID: false
            hostIPC: false
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
            containers:
                - name: operator
                  imagePullPolicy: {{ .Values.operator.imagePullPolicy }}
                  image: {{ .Values.operator.image }}
                  args:
                    - --scope={{ .Values.operator.scope }}
{{- if .Values.operator.features.deployment }}
                    - --operator.deployment
{{- end -}}
{{ if .Values.operator.features.deploymentReplications }}
                    - --operator.deployment-replication
{{- end -}}
{{ if .Values.operator.features.storage }}
                    - --operator.storage
{{- end }}
{{ if .Values.operator.features.backup }}
                    - --operator.backup
{{- end }}
                    - --chaos.allowed={{ .Values.operator.allowChaos }}
{{- if .Values.operator.args }}
{{- range .Values.operator.args }}
                    - {{ . | quote }}
{{- end }}
{{- end }}
                  env:
                      - name: MY_POD_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                      - name: MY_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MY_POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: RELATED_IMAGE_UBI
                        value: "{{ .Values.operator.images.base }}"
                      - name: RELATED_IMAGE_METRICSEXPORTER
                        value: "{{ .Values.operator.images.metricsExporter }}"
                      - name: RELATED_IMAGE_DATABASE
                        value: "{{ .Values.operator.images.arango }}"
                  ports:
                      - name: metrics
                        containerPort: 8528
                  securityContext:
                      privileged: false
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      capabilities:
                          drop:
                              - 'ALL'
{{- if .Values.operator.resources }}
                  resources:
{{ toYaml .Values.operator.resources | indent 22 }}
{{- end }}
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 8528
                          scheme: HTTPS
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 8528
                          scheme: HTTPS
                      initialDelaySeconds: 5
                      periodSeconds: 10
            tolerations:
                - key: "node.kubernetes.io/unreachable"
                  operator: "Exists"
                  effect: "NoExecute"
                  tolerationSeconds: 5
                - key: "node.kubernetes.io/not-ready"
                  operator: "Exists"
                  effect: "NoExecute"
                  tolerationSeconds: 5
