{{- if .Values.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "kube-arangodb.operatorName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
      app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
      helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
      app.kubernetes.io/managed-by: {{ .Release.Service }}
      app.kubernetes.io/instance: {{ .Release.Name }}
      release: {{ .Release.Name }}
{{- if .Values.operator.imagePullSecrets }}
imagePullSecrets:
{{- range .Values.operator.imagePullSecrets }}
  - name: {{ . }}
{{- end }}
{{- end }}
{{- end }}
