{{ if .Values.rbac.enabled -}}
{{ if not (eq .Values.operator.scope "namespaced") -}}
{{ if .Values.operator.enableCRDManagement -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ template "kube-arangodb.rbac-cluster" . }}-crd
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
# analytics.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "graphanalyticsengines.analytics.arangodb.com"
# apps.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangojobs.apps.arangodb.com"
# backup.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangobackuppolicies.backup.arangodb.com"
      - "arangobackups.backup.arangodb.com"
# database.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangoclustersynchronizations.database.arangodb.com"
      - "arangodeployments.database.arangodb.com"
      - "arangomembers.database.arangodb.com"
      - "arangotasks.database.arangodb.com"
# ml.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangomlbatchjobs.ml.arangodb.com"
      - "arangomlcronjobs.ml.arangodb.com"
      - "arangomlextensions.ml.arangodb.com"
      - "arangomlstorages.ml.arangodb.com"
# networking.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangoroutes.networking.arangodb.com"
# replication.database.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangodeploymentreplications.replication.database.arangodb.com"
# scheduler.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: ["get", "list", "watch", "update", "delete"]
    resourceNames:
      - "arangoprofiles.scheduler.arangodb.com"

{{- end }}
{{- end }}
{{- end }}