//
// DISCLAIMER
//
// Copyright 2026 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: integrations/connector/v1/definition/internal.proto

package definition

import (
	context "context"
	definition "github.com/arangodb/kube-arangodb/integrations/shared/v1/definition"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ConnectorV1Internal_PickUpJob_FullMethodName        = "/connector.ConnectorV1Internal/PickUpJob"
	ConnectorV1Internal_GetJob_FullMethodName           = "/connector.ConnectorV1Internal/GetJob"
	ConnectorV1Internal_UpdateJobStatus_FullMethodName  = "/connector.ConnectorV1Internal/UpdateJobStatus"
	ConnectorV1Internal_UploadFile_FullMethodName       = "/connector.ConnectorV1Internal/UploadFile"
	ConnectorV1Internal_BatchUploadFiles_FullMethodName = "/connector.ConnectorV1Internal/BatchUploadFiles"
)

// ConnectorV1InternalClient is the client API for ConnectorV1Internal service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ConnectorV1Internal — used by connector processes to pick up and process jobs (GRPC only)
type ConnectorV1InternalClient interface {
	// Pick up one pending job, atomically moving it to Scheduled. Returns job ID or empty if none
	PickUpJob(ctx context.Context, in *definition.Empty, opts ...grpc.CallOption) (*PickUpJobResponse, error)
	// Get full job details by ID
	GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error)
	// Update job status (Running, Completed, or Failed)
	UpdateJobStatus(ctx context.Context, in *UpdateJobStatusRequest, opts ...grpc.CallOption) (*UpdateJobStatusResponse, error)
	// Upload a single file to a job's FileStore directory
	UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error)
	// Upload multiple files to a job's FileStore directory in one call (streaming, no HTTP)
	BatchUploadFiles(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BatchUploadFileRequest, BatchUploadFilesResponse], error)
}

type connectorV1InternalClient struct {
	cc grpc.ClientConnInterface
}

func NewConnectorV1InternalClient(cc grpc.ClientConnInterface) ConnectorV1InternalClient {
	return &connectorV1InternalClient{cc}
}

func (c *connectorV1InternalClient) PickUpJob(ctx context.Context, in *definition.Empty, opts ...grpc.CallOption) (*PickUpJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PickUpJobResponse)
	err := c.cc.Invoke(ctx, ConnectorV1Internal_PickUpJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorV1InternalClient) GetJob(ctx context.Context, in *GetJobRequest, opts ...grpc.CallOption) (*GetJobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetJobResponse)
	err := c.cc.Invoke(ctx, ConnectorV1Internal_GetJob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorV1InternalClient) UpdateJobStatus(ctx context.Context, in *UpdateJobStatusRequest, opts ...grpc.CallOption) (*UpdateJobStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateJobStatusResponse)
	err := c.cc.Invoke(ctx, ConnectorV1Internal_UpdateJobStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorV1InternalClient) UploadFile(ctx context.Context, in *UploadFileRequest, opts ...grpc.CallOption) (*UploadFileResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UploadFileResponse)
	err := c.cc.Invoke(ctx, ConnectorV1Internal_UploadFile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *connectorV1InternalClient) BatchUploadFiles(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[BatchUploadFileRequest, BatchUploadFilesResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ConnectorV1Internal_ServiceDesc.Streams[0], ConnectorV1Internal_BatchUploadFiles_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[BatchUploadFileRequest, BatchUploadFilesResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorV1Internal_BatchUploadFilesClient = grpc.ClientStreamingClient[BatchUploadFileRequest, BatchUploadFilesResponse]

// ConnectorV1InternalServer is the server API for ConnectorV1Internal service.
// All implementations must embed UnimplementedConnectorV1InternalServer
// for forward compatibility.
//
// ConnectorV1Internal — used by connector processes to pick up and process jobs (GRPC only)
type ConnectorV1InternalServer interface {
	// Pick up one pending job, atomically moving it to Scheduled. Returns job ID or empty if none
	PickUpJob(context.Context, *definition.Empty) (*PickUpJobResponse, error)
	// Get full job details by ID
	GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error)
	// Update job status (Running, Completed, or Failed)
	UpdateJobStatus(context.Context, *UpdateJobStatusRequest) (*UpdateJobStatusResponse, error)
	// Upload a single file to a job's FileStore directory
	UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error)
	// Upload multiple files to a job's FileStore directory in one call (streaming, no HTTP)
	BatchUploadFiles(grpc.ClientStreamingServer[BatchUploadFileRequest, BatchUploadFilesResponse]) error
	mustEmbedUnimplementedConnectorV1InternalServer()
}

// UnimplementedConnectorV1InternalServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedConnectorV1InternalServer struct{}

func (UnimplementedConnectorV1InternalServer) PickUpJob(context.Context, *definition.Empty) (*PickUpJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method PickUpJob not implemented")
}
func (UnimplementedConnectorV1InternalServer) GetJob(context.Context, *GetJobRequest) (*GetJobResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetJob not implemented")
}
func (UnimplementedConnectorV1InternalServer) UpdateJobStatus(context.Context, *UpdateJobStatusRequest) (*UpdateJobStatusResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateJobStatus not implemented")
}
func (UnimplementedConnectorV1InternalServer) UploadFile(context.Context, *UploadFileRequest) (*UploadFileResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadFile not implemented")
}
func (UnimplementedConnectorV1InternalServer) BatchUploadFiles(grpc.ClientStreamingServer[BatchUploadFileRequest, BatchUploadFilesResponse]) error {
	return status.Errorf(codes.Unimplemented, "method BatchUploadFiles not implemented")
}
func (UnimplementedConnectorV1InternalServer) mustEmbedUnimplementedConnectorV1InternalServer() {}
func (UnimplementedConnectorV1InternalServer) testEmbeddedByValue()                             {}

// UnsafeConnectorV1InternalServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ConnectorV1InternalServer will
// result in compilation errors.
type UnsafeConnectorV1InternalServer interface {
	mustEmbedUnimplementedConnectorV1InternalServer()
}

func RegisterConnectorV1InternalServer(s grpc.ServiceRegistrar, srv ConnectorV1InternalServer) {
	// If the following call pancis, it indicates UnimplementedConnectorV1InternalServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ConnectorV1Internal_ServiceDesc, srv)
}

func _ConnectorV1Internal_PickUpJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(definition.Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorV1InternalServer).PickUpJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorV1Internal_PickUpJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorV1InternalServer).PickUpJob(ctx, req.(*definition.Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorV1Internal_GetJob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetJobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorV1InternalServer).GetJob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorV1Internal_GetJob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorV1InternalServer).GetJob(ctx, req.(*GetJobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorV1Internal_UpdateJobStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateJobStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorV1InternalServer).UpdateJobStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorV1Internal_UpdateJobStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorV1InternalServer).UpdateJobStatus(ctx, req.(*UpdateJobStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorV1Internal_UploadFile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadFileRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ConnectorV1InternalServer).UploadFile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ConnectorV1Internal_UploadFile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ConnectorV1InternalServer).UploadFile(ctx, req.(*UploadFileRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ConnectorV1Internal_BatchUploadFiles_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ConnectorV1InternalServer).BatchUploadFiles(&grpc.GenericServerStream[BatchUploadFileRequest, BatchUploadFilesResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ConnectorV1Internal_BatchUploadFilesServer = grpc.ClientStreamingServer[BatchUploadFileRequest, BatchUploadFilesResponse]

// ConnectorV1Internal_ServiceDesc is the grpc.ServiceDesc for ConnectorV1Internal service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ConnectorV1Internal_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "connector.ConnectorV1Internal",
	HandlerType: (*ConnectorV1InternalServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PickUpJob",
			Handler:    _ConnectorV1Internal_PickUpJob_Handler,
		},
		{
			MethodName: "GetJob",
			Handler:    _ConnectorV1Internal_GetJob_Handler,
		},
		{
			MethodName: "UpdateJobStatus",
			Handler:    _ConnectorV1Internal_UpdateJobStatus_Handler,
		},
		{
			MethodName: "UploadFile",
			Handler:    _ConnectorV1Internal_UploadFile_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "BatchUploadFiles",
			Handler:       _ConnectorV1Internal_BatchUploadFiles_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "integrations/connector/v1/definition/internal.proto",
}
