version: 2.1

# dummy file - nothing to be done for CI here

jobs:
  print-ok:
    docker:
      - image: alpine:3.13
    steps:
      - run: echo "ok"

workflows:
  always_ok:
    jobs:
      - print-ok
