version: 2.1

orbs:
  path-filtering: circleci/path-filtering@1.0.0

setup: true

parameters:
  manifests-verify:
    type: boolean
    default: false

workflows:
  always-run:
    jobs:
      - path-filtering/filter:
          name: check-updated-files
          base-revision: master
          config-path: .circleci/continue_config.yml
          mapping: |
            manifests/.* manifests-verify true
            chart/.* manifests-verify true
