---
{{- $secretName := printf "%s-root-credentials" (include "platform-storage.releaseName" .) -}}
{{- $existing := lookup "v1" "Secret" .Release.Namespace $secretName -}}

{{- $password := "" -}}
{{- if $existing -}}
  {{- $password = index $existing.data "MINIO_ROOT_PASSWORD" | b64dec -}}
{{- else -}}
  {{- $password = randAlphaNum 32 -}}
{{- end -}}

apiVersion: v1
kind: Secret
metadata:
  name: {{ $secretName }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "platform-storage.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  MINIO_ROOT_USER: {{ "minioadmin" | b64enc | quote }}
  MINIO_ROOT_PASSWORD: {{ $password | b64enc | quote }}

---

apiVersion: v1
kind: Secret
metadata:
  name: "{{ template "platform-storage.releaseName" . }}-credentials"
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ template "platform-storage.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
type: Opaque
data:
  accessKey: {{ "minioadmin" | b64enc | quote }}
  secretKey: {{ $password | b64enc | quote }}