---
# Source: kube-arangodb-crd/templates/job.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangojobs.apps.arangodb.com
  labels:
    app.kubernetes.io/name: kube-arangodb-crd
    helm.sh/chart: kube-arangodb-crd-1.2.4
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: crd
    release: crd
spec:
  group: apps.arangodb.com
  names:
    kind: ArangoJob
    listKind: ArangoJobList
    plural: arangojobs
    singular: arangojob
    shortNames:
      - arangojob
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.arangoDeploymentName
          description: Deployment name
          name: ArangoDeploymentName
          type: string
      subresources:
        status: {}
