# File: chart/kube-arangodb/crds/apps-job.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangojobs.apps.arangodb.com
spec:
  group: apps.arangodb.com
  names:
    kind: ArangoJob
    listKind: ArangoJobList
    plural: arangojobs
    singular: arangojob
    shortNames:
      - arangojob
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.arangoDeploymentName
          description: Deployment name
          name: ArangoDeploymentName
          type: string
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/backups-backup.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangobackups.backup.arangodb.com
spec:
  group: backup.arangodb.com
  names:
    kind: ArangoBackup
    listKind: ArangoBackupList
    plural: arangobackups
    shortNames:
      - arangobackup
    singular: arangobackup
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.policyName
          description: Policy name
          name: Policy
          type: string
        - jsonPath: .spec.deployment.name
          description: Deployment name
          name: Deployment
          type: string
        - jsonPath: .status.backup.version
          description: Backup Version
          name: Version
          type: string
        - jsonPath: .status.backup.createdAt
          description: Backup Creation Timestamp
          name: Created
          type: string
        - jsonPath: .status.backup.sizeInBytes
          description: Backup Size in Bytes
          name: Size
          type: integer
          format: byte
        - jsonPath: .status.backup.numberOfDBServers
          description: Backup Number of the DB Servers
          name: DBServers
          type: integer
        - jsonPath: .status.state
          description: The actual state of the ArangoBackup
          name: State
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackup object
          name: Message
          type: string
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/backups-backuppolicy.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangobackuppolicies.backup.arangodb.com
spec:
  group: backup.arangodb.com
  names:
    kind: ArangoBackupPolicy
    listKind: ArangoBackupPolicyList
    plural: arangobackuppolicies
    shortNames:
      - arangobackuppolicy
      - arangobp
    singular: arangobackuppolicy
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.schedule
          description: Schedule
          name: Schedule
          type: string
        - jsonPath: .status.scheduled
          description: Scheduled
          name: Scheduled
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackupPolicy object
          name: Message
          type: string
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-clustersynchronization.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoclustersynchronizations.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoClusterSynchronization
    listKind: ArangoClusterSynchronizationList
    plural: arangoclustersynchronizations
    singular: arangoclustersynchronization
    shortNames:
      - arangoclustersync
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-deployment.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangodeployments.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoDeployment
    listKind: ArangoDeploymentList
    plural: arangodeployments
    shortNames:
      - arangodb
      - arango
    singular: arangodeployment
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-member.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomembers.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoMember
    listKind: ArangoMemberList
    plural: arangomembers
    shortNames:
      - arangomembers
    singular: arangomember
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/database-task.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangotasks.database.arangodb.com
spec:
  group: database.arangodb.com
  names:
    kind: ArangoTask
    listKind: ArangoTaskList
    plural: arangotasks
    singular: arangotask
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/replication-deploymentreplication.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangodeploymentreplications.replication.database.arangodb.com
spec:
  group: replication.database.arangodb.com
  names:
    kind: ArangoDeploymentReplication
    listKind: ArangoDeploymentReplicationList
    plural: arangodeploymentreplications
    shortNames:
      - arangorepl
    singular: arangodeploymentreplication
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/ml-storage.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomlstorages.ml.arangodb.com
spec:
  group: ml.arangodb.com
  names:
    kind: ArangoMLStorage
    listKind: ArangoMLStorageList
    plural: arangomlstorages
    singular: arangomlstorage
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/ml-extension.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomlextensions.ml.arangodb.com
spec:
  group: ml.arangodb.com
  names:
    kind: ArangoMLExtension
    listKind: ArangoMLExtensionList
    plural: arangomlextensions
    singular: arangomlextension
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/ml-job-batch.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomlbatchjobs.ml.arangodb.com
spec:
  group: ml.arangodb.com
  names:
    kind: ArangoMLBatchJob
    listKind: ArangoMLBatchJobList
    plural: arangomlbatchjobs
    singular: arangomlbatchjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/ml-job-cron.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomlcronjobs.ml.arangodb.com
spec:
  group: ml.arangodb.com
  names:
    kind: ArangoMLCronJob
    listKind: ArangoMLCronJobList
    plural: arangomlcronjobs
    singular: arangomlcronjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/scheduler-profile.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoprofiles.scheduler.arangodb.com
spec:
  group: scheduler.arangodb.com
  names:
    kind: ArangoProfile
    listKind: ArangoProfileList
    plural: arangoprofiles
    singular: arangoprofile
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/scheduler-pod.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoschedulerpods.scheduler.arangodb.com
spec:
  group: scheduler.arangodb.com
  names:
    kind: ArangoSchedulerPod
    listKind: ArangoSchedulerPodList
    plural: arangoschedulerpods
    singular: arangoschedulerpod
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/scheduler-deployment.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoschedulerdeployments.scheduler.arangodb.com
spec:
  group: scheduler.arangodb.com
  names:
    kind: ArangoSchedulerDeployment
    listKind: ArangoSchedulerDeploymentList
    plural: arangoschedulerdeployments
    singular: arangoschedulerdeployment
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
---
# File: chart/kube-arangodb/crds/scheduler-batchjob.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoschedulerbatchjobs.scheduler.arangodb.com
spec:
  group: scheduler.arangodb.com
  names:
    kind: ArangoSchedulerBatchJob
    listKind: ArangoSchedulerBatchJobList
    plural: arangoschedulerbatchjobs
    singular: arangoschedulerbatchjob
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/scheduler-cronjob.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoschedulercronjobs.scheduler.arangodb.com
spec:
  group: scheduler.arangodb.com
  names:
    kind: ArangoSchedulerCronJob
    listKind: ArangoSchedulerCronJobList
    plural: arangoschedulercronjobs
    singular: arangoschedulercronjob
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/analytics-graphanalyticsengine.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: graphanalyticsengines.analytics.arangodb.com
spec:
  group: analytics.arangodb.com
  names:
    kind: GraphAnalyticsEngine
    listKind: GraphAnalyticsEngineList
    plural: graphanalyticsengines
    singular: graphanalyticsengine
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/networking-route.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoroutes.networking.arangodb.com
spec:
  group: networking.arangodb.com
  names:
    kind: ArangoRoute
    listKind: ArangoRouteList
    plural: arangoroutes
    singular: arangoroute
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/platform-storage.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoplatformstorages.platform.arangodb.com
spec:
  group: platform.arangodb.com
  names:
    kind: ArangoPlatformStorage
    listKind: ArangoPlatformStorageList
    plural: arangoplatformstorages
    singular: arangoplatformstorage
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
---
# File: chart/kube-arangodb/crds/platform-chart.yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoplatformcharts.platform.arangodb.com
spec:
  group: platform.arangodb.com
  names:
    kind: ArangoPlatformChart
    listKind: ArangoPlatformChartList
    plural: arangoplatformcharts
    singular: arangoplatformchart
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
        scale:
          specReplicasPath: .spec.replicas
          statusReplicasPath: .status.replicas
