{{ if .Values.rbac.enabled -}}
{{ if not (eq .Values.operator.scope "namespaced") -}}
{{ if .Values.operator.enableCRDManagement -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ template "kube-arangodb.rbac-cluster" . }}-crd
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
{{ if .Values.operator.features.analytics -}}
# analytics.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "graphanalyticsengines.analytics.arangodb.com"
{{- end }}
{{ if .Values.operator.features.apps -}}
# apps.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangojobs.apps.arangodb.com"
{{- end }}
{{ if .Values.operator.features.backup -}}
# backup.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangobackuppolicies.backup.arangodb.com"
      - "arangobackups.backup.arangodb.com"
{{- end }}
{{ if .Values.operator.features.deployment -}}
# database.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangoclustersynchronizations.database.arangodb.com"
      - "arangodeployments.database.arangodb.com"
      - "arangomembers.database.arangodb.com"
      - "arangotasks.database.arangodb.com"
{{- end }}
{{ if .Values.operator.features.ml -}}
# ml.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangomlbatchjobs.ml.arangodb.com"
      - "arangomlcronjobs.ml.arangodb.com"
      - "arangomlextensions.ml.arangodb.com"
      - "arangomlstorages.ml.arangodb.com"
{{- end }}
{{ if .Values.operator.features.networking -}}
# networking.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangoroutes.networking.arangodb.com"
{{- end }}
{{ if .Values.operator.features.deploymentReplications -}}
# replication.database.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangodeploymentreplications.replication.database.arangodb.com"
{{- end }}
{{ if .Values.operator.features.scheduler -}}
# scheduler.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangoprofiles.scheduler.arangodb.com"
      - "arangoschedulerpods.scheduler.arangodb.com"
      - "arangoschedulerdeploymets.scheduler.arangodb.com"
      - "arangoschedulerbatchjobs.scheduler.arangodb.com"
      - "arangoschedulercronjobs.scheduler.arangodb.com"
{{- end }}
{{ if .Values.operator.features.platform -}}
# platform.arangodb.com
  - apiGroups: ["apiextensions.k8s.io"]
    resources: ["customresourcedefinitions"]
    verbs: [{{ if .Values.operator.enableCRDCreation }}"create", {{ end }}"get", "list", "watch", "update"]
    resourceNames:
      - "arangoplatformcharts.platform.arangodb.com"
      - "arangoplatformstorages.platform.arangodb.com"
      - "arangoplatformservices.platform.arangodb.com"
{{- end }}

{{- end }}
{{- end }}
{{- end }}