{{ if .Values.rbac.enabled -}}
{{ if not (eq .Values.operator.scope "namespaced") -}}
{{ if .Values.operator.features.k8sToK8sClusterSync -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: {{ template "kube-arangodb.rbac-cluster" . }}-k2kclustersync
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: {{ template "kube-arangodb.rbac-cluster" . }}-k2kclustersync
subjects:
    - kind: ServiceAccount
      name: {{ template "kube-arangodb.operatorName" . }}
      namespace: {{ .Release.Namespace }}

{{- end }}
{{- end }}
{{- end }}
