operator:
  image: arangodb/kube-arangodb-enterprise:1.3.0
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  scope: legacy
  architectures:
    - amd64
  debug: false
  args: []
  service:
    type: ClusterIP
  annotations: {}
  resources:
    limits:
      cpu: 1
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  securityContext:
    runAsUser: 1000
  replicaCount: 1
  updateStrategy:
    type: Recreate
  allowChaos: false
  nodeSelector: {}
  enableCRDManagement: true
  features:
    deployment: true
    deploymentReplications: true
    storage: false
    storageCRD: true
    backup: false
    apps: false
    k8sToK8sClusterSync: false
    ml: true
    analytics: false
    networking: true
    scheduler: true
    platform: true
  tolerations: []
rbac:
  enabled: true
  extensions:
    monitoring: true
    acs: true
    at: true
    debug: false
webhooks:
  enabled: false
  args: []
  resources:
    limits:
      cpu: 1
      memory: 128Mi
    requests:
      cpu: 250m
      memory: 128Mi
certificate:
  enabled: false
  ca:
    duration: 43800h
    commonName: "kube-arangodb.operator.cert"
  cert:
    duration: 8760h
