apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
    name: arangobackuppolicies.backup.arangodb.com
spec:
    group: backup.arangodb.com
    additionalPrinterColumns:
        - JSONPath: .spec.schedule
          description: Schedule
          name: Schedule
          type: string
        - JSONPath: .status.scheduled
          description: Scheduled
          name: Scheduled
          type: string
        - JSONPath: .status.message
          priority: 1
          description: Message of the ArangoBackupPolicy object
          name: Message
          type: string
    names:
        kind: ArangoBackupPolicy
        listKind: ArangoBackupPolicyList
        plural: arangobackuppolicies
        shortNames:
            - arangobackuppolicy
            - arangobp
        singular: arangobackuppolicy
    scope: Namespaced
    subresources:
        status: {}
    version: v1
    versions:
      - name: v1
        served: true
        storage: true
      - name: v1alpha
        served: true
        storage: false
