apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoschedulerpods.scheduler.arangodb.com
spec:
  group: scheduler.arangodb.com
  names:
    kind: ArangoSchedulerPod
    listKind: ArangoSchedulerPodList
    plural: arangoschedulerpods
    singular: arangoschedulerpod
  scope: Namespaced
  versions:
    - name: v1beta1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
