apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangobackuppolicies.backup.arangodb.com
  labels:
    app.kubernetes.io/name: {{ template "kube-arangodb-crd.name" . }}
    helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    release: {{ .Release.Name }}
spec:
  group: backup.arangodb.com
  names:
    kind: ArangoBackupPolicy
    listKind: ArangoBackupPolicyList
    plural: arangobackuppolicies
    shortNames:
      - arangobackuppolicy
      - arangobp
    singular: arangobackuppolicy
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: .spec.schedule
          description: Schedule
          name: Schedule
          type: string
        - jsonPath: .status.scheduled
          description: Scheduled
          name: Scheduled
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackupPolicy object
          name: Message
          type: string
      subresources:
        status: {}
    - name: v1alpha
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      additionalPrinterColumns:
        - jsonPath: .spec.schedule
          description: Schedule
          name: Schedule
          type: string
        - jsonPath: .status.scheduled
          description: Scheduled
          name: Scheduled
          type: string
        - jsonPath: .status.message
          priority: 1
          description: Message of the ArangoBackupPolicy object
          name: Message
          type: string
      subresources:
        status: {}
