apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
    name: arangomembers.database.arangodb.com
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb-crd.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
spec:
  group: database.arangodb.com
  names:
    kind: ArangoMember
    listKind: ArangoMemberList
    plural: arangomembers
    shortNames:
      - arangomembers
    singular: arangomember
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
    - name: v2alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: false
      subresources:
        status: {}