{{ if .Values.rbac.enabled -}}
{{ if .Values.operator.features.deploymentReplications -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ template "kube-arangodb.rbac" . }}-deployment-replication
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["namespaces", "nodes"]
      verbs: ["get", "list"]

{{- end }}
{{- end }}