{{ if .Values.rbac.enabled -}}
{{ if .Values.operator.features.deploymentReplications -}}

apiVersion: rbac.authorization.k8s.io/v1
{{ if not (eq .Values.operator.scope "cluster") }}
kind: Role
{{ else }}
kind: ClusterRole
{{ end }}
metadata:
    name: {{ template "kube-arangodb.rbac" . }}-deployment-replication
    {{ if not (eq .Values.operator.scope "cluster") }}
    namespace: {{ .Release.Namespace }}
    {{ end }}
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
    - apiGroups: ["replication.database.arangodb.com"]
      resources: ["arangodeploymentreplications", "arangodeploymentreplications/status"]
      verbs: ["*"]
    - apiGroups: ["database.arangodb.com"]
      resources: ["arangodeployments"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "secrets"]
      verbs: ["*"]
    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get"]

{{- end }}
{{- end }}