//go:build !ignore_autogenerated
// +build !ignore_autogenerated

//
// DISCLAIMER
//
// Copyright 2026 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by deepcopy-gen. DO NOT EDIT.

package v1beta1

import (
	v1 "github.com/arangodb/kube-arangodb/pkg/apis/shared/v1"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformChart) DeepCopyInto(out *ArangoPlatformChart) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformChart.
func (in *ArangoPlatformChart) DeepCopy() *ArangoPlatformChart {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformChart)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPlatformChart) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformChartList) DeepCopyInto(out *ArangoPlatformChartList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPlatformChart, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformChartList.
func (in *ArangoPlatformChartList) DeepCopy() *ArangoPlatformChartList {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformChartList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPlatformChartList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformChartSpec) DeepCopyInto(out *ArangoPlatformChartSpec) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = make(v1.Data, len(*in))
		copy(*out, *in)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(v1.Any, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformChartSpec.
func (in *ArangoPlatformChartSpec) DeepCopy() *ArangoPlatformChartSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformChartSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformChartStatus) DeepCopyInto(out *ArangoPlatformChartStatus) {
	*out = *in
	if in.Info != nil {
		in, out := &in.Info, &out.Info
		*out = new(ChartStatusInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformChartStatus.
func (in *ArangoPlatformChartStatus) DeepCopy() *ArangoPlatformChartStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformChartStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformService) DeepCopyInto(out *ArangoPlatformService) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformService.
func (in *ArangoPlatformService) DeepCopy() *ArangoPlatformService {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformService)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPlatformService) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceList) DeepCopyInto(out *ArangoPlatformServiceList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPlatformService, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceList.
func (in *ArangoPlatformServiceList) DeepCopy() *ArangoPlatformServiceList {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPlatformServiceList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceSpec) DeepCopyInto(out *ArangoPlatformServiceSpec) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Chart != nil {
		in, out := &in.Chart, &out.Chart
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(v1.Any, len(*in))
		copy(*out, *in)
	}
	if in.Upgrade != nil {
		in, out := &in.Upgrade, &out.Upgrade
		*out = new(ArangoPlatformServiceSpecUpgrade)
		(*in).DeepCopyInto(*out)
	}
	if in.Install != nil {
		in, out := &in.Install, &out.Install
		*out = new(ArangoPlatformServiceSpecInstall)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceSpec.
func (in *ArangoPlatformServiceSpec) DeepCopy() *ArangoPlatformServiceSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceSpecInstall) DeepCopyInto(out *ArangoPlatformServiceSpecInstall) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceSpecInstall.
func (in *ArangoPlatformServiceSpecInstall) DeepCopy() *ArangoPlatformServiceSpecInstall {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceSpecInstall)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceSpecUpgrade) DeepCopyInto(out *ArangoPlatformServiceSpecUpgrade) {
	*out = *in
	if in.Timeout != nil {
		in, out := &in.Timeout, &out.Timeout
		*out = new(metav1.Duration)
		**out = **in
	}
	if in.MaxHistory != nil {
		in, out := &in.MaxHistory, &out.MaxHistory
		*out = new(int)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceSpecUpgrade.
func (in *ArangoPlatformServiceSpecUpgrade) DeepCopy() *ArangoPlatformServiceSpecUpgrade {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceSpecUpgrade)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceStatus) DeepCopyInto(out *ArangoPlatformServiceStatus) {
	*out = *in
	if in.Deployment != nil {
		in, out := &in.Deployment, &out.Deployment
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Chart != nil {
		in, out := &in.Chart, &out.Chart
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Values != nil {
		in, out := &in.Values, &out.Values
		*out = make(v1.Any, len(*in))
		copy(*out, *in)
	}
	if in.ChartInfo != nil {
		in, out := &in.ChartInfo, &out.ChartInfo
		*out = new(ChartStatusInfo)
		(*in).DeepCopyInto(*out)
	}
	if in.Release != nil {
		in, out := &in.Release, &out.Release
		*out = new(ArangoPlatformServiceStatusRelease)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceStatus.
func (in *ArangoPlatformServiceStatus) DeepCopy() *ArangoPlatformServiceStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceStatusRelease) DeepCopyInto(out *ArangoPlatformServiceStatusRelease) {
	*out = *in
	in.Info.DeepCopyInto(&out.Info)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceStatusRelease.
func (in *ArangoPlatformServiceStatusRelease) DeepCopy() *ArangoPlatformServiceStatusRelease {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceStatusRelease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformServiceStatusReleaseInfo) DeepCopyInto(out *ArangoPlatformServiceStatusReleaseInfo) {
	*out = *in
	if in.FirstDeployed != nil {
		in, out := &in.FirstDeployed, &out.FirstDeployed
		*out = (*in).DeepCopy()
	}
	if in.LastDeployed != nil {
		in, out := &in.LastDeployed, &out.LastDeployed
		*out = (*in).DeepCopy()
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformServiceStatusReleaseInfo.
func (in *ArangoPlatformServiceStatusReleaseInfo) DeepCopy() *ArangoPlatformServiceStatusReleaseInfo {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformServiceStatusReleaseInfo)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorage) DeepCopyInto(out *ArangoPlatformStorage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorage.
func (in *ArangoPlatformStorage) DeepCopy() *ArangoPlatformStorage {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPlatformStorage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageList) DeepCopyInto(out *ArangoPlatformStorageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ArangoPlatformStorage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageList.
func (in *ArangoPlatformStorageList) DeepCopy() *ArangoPlatformStorageList {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ArangoPlatformStorageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpec) DeepCopyInto(out *ArangoPlatformStorageSpec) {
	*out = *in
	if in.Backend != nil {
		in, out := &in.Backend, &out.Backend
		*out = new(ArangoPlatformStorageSpecBackend)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpec.
func (in *ArangoPlatformStorageSpec) DeepCopy() *ArangoPlatformStorageSpec {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpecBackend) DeepCopyInto(out *ArangoPlatformStorageSpecBackend) {
	*out = *in
	if in.S3 != nil {
		in, out := &in.S3, &out.S3
		*out = new(ArangoPlatformStorageSpecBackendS3)
		(*in).DeepCopyInto(*out)
	}
	if in.GCS != nil {
		in, out := &in.GCS, &out.GCS
		*out = new(ArangoPlatformStorageSpecBackendGCS)
		(*in).DeepCopyInto(*out)
	}
	if in.AzureBlobStorage != nil {
		in, out := &in.AzureBlobStorage, &out.AzureBlobStorage
		*out = new(ArangoPlatformStorageSpecBackendAzureBlobStorage)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpecBackend.
func (in *ArangoPlatformStorageSpecBackend) DeepCopy() *ArangoPlatformStorageSpecBackend {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpecBackend)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpecBackendAzureBlobStorage) DeepCopyInto(out *ArangoPlatformStorageSpecBackendAzureBlobStorage) {
	*out = *in
	if in.TenantID != nil {
		in, out := &in.TenantID, &out.TenantID
		*out = new(string)
		**out = **in
	}
	if in.AccountName != nil {
		in, out := &in.AccountName, &out.AccountName
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.BucketPrefix != nil {
		in, out := &in.BucketPrefix, &out.BucketPrefix
		*out = new(string)
		**out = **in
	}
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpecBackendAzureBlobStorage.
func (in *ArangoPlatformStorageSpecBackendAzureBlobStorage) DeepCopy() *ArangoPlatformStorageSpecBackendAzureBlobStorage {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpecBackendAzureBlobStorage)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpecBackendGCS) DeepCopyInto(out *ArangoPlatformStorageSpecBackendGCS) {
	*out = *in
	if in.ProjectID != nil {
		in, out := &in.ProjectID, &out.ProjectID
		*out = new(string)
		**out = **in
	}
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.BucketPrefix != nil {
		in, out := &in.BucketPrefix, &out.BucketPrefix
		*out = new(string)
		**out = **in
	}
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpecBackendGCS.
func (in *ArangoPlatformStorageSpecBackendGCS) DeepCopy() *ArangoPlatformStorageSpecBackendGCS {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpecBackendGCS)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpecBackendS3) DeepCopyInto(out *ArangoPlatformStorageSpecBackendS3) {
	*out = *in
	if in.BucketName != nil {
		in, out := &in.BucketName, &out.BucketName
		*out = new(string)
		**out = **in
	}
	if in.BucketPrefix != nil {
		in, out := &in.BucketPrefix, &out.BucketPrefix
		*out = new(string)
		**out = **in
	}
	if in.Endpoint != nil {
		in, out := &in.Endpoint, &out.Endpoint
		*out = new(string)
		**out = **in
	}
	if in.CredentialsSecret != nil {
		in, out := &in.CredentialsSecret, &out.CredentialsSecret
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.AllowInsecure != nil {
		in, out := &in.AllowInsecure, &out.AllowInsecure
		*out = new(bool)
		**out = **in
	}
	if in.CASecret != nil {
		in, out := &in.CASecret, &out.CASecret
		*out = new(v1.Object)
		(*in).DeepCopyInto(*out)
	}
	if in.Region != nil {
		in, out := &in.Region, &out.Region
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpecBackendS3.
func (in *ArangoPlatformStorageSpecBackendS3) DeepCopy() *ArangoPlatformStorageSpecBackendS3 {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpecBackendS3)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpecMode) DeepCopyInto(out *ArangoPlatformStorageSpecMode) {
	*out = *in
	if in.Sidecar != nil {
		in, out := &in.Sidecar, &out.Sidecar
		*out = new(ArangoPlatformStorageSpecModeSidecar)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpecMode.
func (in *ArangoPlatformStorageSpecMode) DeepCopy() *ArangoPlatformStorageSpecMode {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpecMode)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageSpecModeSidecar) DeepCopyInto(out *ArangoPlatformStorageSpecModeSidecar) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageSpecModeSidecar.
func (in *ArangoPlatformStorageSpecModeSidecar) DeepCopy() *ArangoPlatformStorageSpecModeSidecar {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageSpecModeSidecar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ArangoPlatformStorageStatus) DeepCopyInto(out *ArangoPlatformStorageStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make(v1.ConditionList, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ArangoPlatformStorageStatus.
func (in *ArangoPlatformStorageStatus) DeepCopy() *ArangoPlatformStorageStatus {
	if in == nil {
		return nil
	}
	out := new(ArangoPlatformStorageStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartDetails) DeepCopyInto(out *ChartDetails) {
	*out = *in
	if in.Platform != nil {
		in, out := &in.Platform, &out.Platform
		*out = new(ChartDetailsPlatform)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartDetails.
func (in *ChartDetails) DeepCopy() *ChartDetails {
	if in == nil {
		return nil
	}
	out := new(ChartDetails)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartDetailsPlatform) DeepCopyInto(out *ChartDetailsPlatform) {
	*out = *in
	if in.Requirements != nil {
		in, out := &in.Requirements, &out.Requirements
		*out = make(ChartDetailsPlatformRequirements, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartDetailsPlatform.
func (in *ChartDetailsPlatform) DeepCopy() *ChartDetailsPlatform {
	if in == nil {
		return nil
	}
	out := new(ChartDetailsPlatform)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in ChartDetailsPlatformRequirements) DeepCopyInto(out *ChartDetailsPlatformRequirements) {
	{
		in := &in
		*out = make(ChartDetailsPlatformRequirements, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
		return
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartDetailsPlatformRequirements.
func (in ChartDetailsPlatformRequirements) DeepCopy() ChartDetailsPlatformRequirements {
	if in == nil {
		return nil
	}
	out := new(ChartDetailsPlatformRequirements)
	in.DeepCopyInto(out)
	return *out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ChartStatusInfo) DeepCopyInto(out *ChartStatusInfo) {
	*out = *in
	if in.Definition != nil {
		in, out := &in.Definition, &out.Definition
		*out = make(v1.Data, len(*in))
		copy(*out, *in)
	}
	if in.Details != nil {
		in, out := &in.Details, &out.Details
		*out = new(ChartDetails)
		(*in).DeepCopyInto(*out)
	}
	if in.Overrides != nil {
		in, out := &in.Overrides, &out.Overrides
		*out = make(v1.Any, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ChartStatusInfo.
func (in *ChartStatusInfo) DeepCopy() *ChartStatusInfo {
	if in == nil {
		return nil
	}
	out := new(ChartStatusInfo)
	in.DeepCopyInto(out)
	return out
}
