storage:
  class: ""
  size: 5Gi
minio:
  image: minio/minio:latest
  imagePullPolicy: IfNotPresent
  imagePullSecrets: []
  resources:
    limits:
      cpu: 250m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 512Mi
  nodeSelector: {}
  tolerations: []
deployment:
  name: ""
