//
// DISCLAIMER
//
// Copyright 2026 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.0
// source: pkg/sidecar/services/authorization/definition/api.proto

package definition

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AuthorizationAPI_APIGetPolicy_FullMethodName    = "/service.AuthorizationAPI/APIGetPolicy"
	AuthorizationAPI_APIDeletePolicy_FullMethodName = "/service.AuthorizationAPI/APIDeletePolicy"
	AuthorizationAPI_APICreatePolicy_FullMethodName = "/service.AuthorizationAPI/APICreatePolicy"
	AuthorizationAPI_APIUpdatePolicy_FullMethodName = "/service.AuthorizationAPI/APIUpdatePolicy"
	AuthorizationAPI_APIGetRole_FullMethodName      = "/service.AuthorizationAPI/APIGetRole"
	AuthorizationAPI_APIDeleteRole_FullMethodName   = "/service.AuthorizationAPI/APIDeleteRole"
	AuthorizationAPI_APICreateRole_FullMethodName   = "/service.AuthorizationAPI/APICreateRole"
	AuthorizationAPI_APIUpdateRole_FullMethodName   = "/service.AuthorizationAPI/APIUpdateRole"
)

// AuthorizationAPIClient is the client API for AuthorizationAPI service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// AuthorizationAPI Service implementation
type AuthorizationAPIClient interface {
	// Return the Policy
	APIGetPolicy(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error)
	// Delete the Policy
	APIDeletePolicy(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error)
	// Create the Policy
	APICreatePolicy(ctx context.Context, in *AuthorizationAPIPolicyRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error)
	// Update the Policy
	APIUpdatePolicy(ctx context.Context, in *AuthorizationAPIPolicyRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error)
	// Returns the Role
	APIGetRole(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error)
	// Delete the Role
	APIDeleteRole(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error)
	// Create the Role
	APICreateRole(ctx context.Context, in *AuthorizationAPIRoleRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error)
	// Update the Role
	APIUpdateRole(ctx context.Context, in *AuthorizationAPIRoleRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error)
}

type authorizationAPIClient struct {
	cc grpc.ClientConnInterface
}

func NewAuthorizationAPIClient(cc grpc.ClientConnInterface) AuthorizationAPIClient {
	return &authorizationAPIClient{cc}
}

func (c *authorizationAPIClient) APIGetPolicy(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIPolicyResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APIGetPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APIDeletePolicy(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIPolicyResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APIDeletePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APICreatePolicy(ctx context.Context, in *AuthorizationAPIPolicyRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIPolicyResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APICreatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APIUpdatePolicy(ctx context.Context, in *AuthorizationAPIPolicyRequest, opts ...grpc.CallOption) (*AuthorizationAPIPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIPolicyResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APIUpdatePolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APIGetRole(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIRoleResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APIGetRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APIDeleteRole(ctx context.Context, in *AuthorizationAPINamedRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIRoleResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APIDeleteRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APICreateRole(ctx context.Context, in *AuthorizationAPIRoleRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIRoleResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APICreateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authorizationAPIClient) APIUpdateRole(ctx context.Context, in *AuthorizationAPIRoleRequest, opts ...grpc.CallOption) (*AuthorizationAPIRoleResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AuthorizationAPIRoleResponse)
	err := c.cc.Invoke(ctx, AuthorizationAPI_APIUpdateRole_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AuthorizationAPIServer is the server API for AuthorizationAPI service.
// All implementations must embed UnimplementedAuthorizationAPIServer
// for forward compatibility.
//
// AuthorizationAPI Service implementation
type AuthorizationAPIServer interface {
	// Return the Policy
	APIGetPolicy(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIPolicyResponse, error)
	// Delete the Policy
	APIDeletePolicy(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIPolicyResponse, error)
	// Create the Policy
	APICreatePolicy(context.Context, *AuthorizationAPIPolicyRequest) (*AuthorizationAPIPolicyResponse, error)
	// Update the Policy
	APIUpdatePolicy(context.Context, *AuthorizationAPIPolicyRequest) (*AuthorizationAPIPolicyResponse, error)
	// Returns the Role
	APIGetRole(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIRoleResponse, error)
	// Delete the Role
	APIDeleteRole(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIRoleResponse, error)
	// Create the Role
	APICreateRole(context.Context, *AuthorizationAPIRoleRequest) (*AuthorizationAPIRoleResponse, error)
	// Update the Role
	APIUpdateRole(context.Context, *AuthorizationAPIRoleRequest) (*AuthorizationAPIRoleResponse, error)
	mustEmbedUnimplementedAuthorizationAPIServer()
}

// UnimplementedAuthorizationAPIServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAuthorizationAPIServer struct{}

func (UnimplementedAuthorizationAPIServer) APIGetPolicy(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIGetPolicy not implemented")
}
func (UnimplementedAuthorizationAPIServer) APIDeletePolicy(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIDeletePolicy not implemented")
}
func (UnimplementedAuthorizationAPIServer) APICreatePolicy(context.Context, *AuthorizationAPIPolicyRequest) (*AuthorizationAPIPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APICreatePolicy not implemented")
}
func (UnimplementedAuthorizationAPIServer) APIUpdatePolicy(context.Context, *AuthorizationAPIPolicyRequest) (*AuthorizationAPIPolicyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIUpdatePolicy not implemented")
}
func (UnimplementedAuthorizationAPIServer) APIGetRole(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIGetRole not implemented")
}
func (UnimplementedAuthorizationAPIServer) APIDeleteRole(context.Context, *AuthorizationAPINamedRequest) (*AuthorizationAPIRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIDeleteRole not implemented")
}
func (UnimplementedAuthorizationAPIServer) APICreateRole(context.Context, *AuthorizationAPIRoleRequest) (*AuthorizationAPIRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APICreateRole not implemented")
}
func (UnimplementedAuthorizationAPIServer) APIUpdateRole(context.Context, *AuthorizationAPIRoleRequest) (*AuthorizationAPIRoleResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method APIUpdateRole not implemented")
}
func (UnimplementedAuthorizationAPIServer) mustEmbedUnimplementedAuthorizationAPIServer() {}
func (UnimplementedAuthorizationAPIServer) testEmbeddedByValue()                          {}

// UnsafeAuthorizationAPIServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AuthorizationAPIServer will
// result in compilation errors.
type UnsafeAuthorizationAPIServer interface {
	mustEmbedUnimplementedAuthorizationAPIServer()
}

func RegisterAuthorizationAPIServer(s grpc.ServiceRegistrar, srv AuthorizationAPIServer) {
	// If the following call pancis, it indicates UnimplementedAuthorizationAPIServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AuthorizationAPI_ServiceDesc, srv)
}

func _AuthorizationAPI_APIGetPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPINamedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APIGetPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APIGetPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APIGetPolicy(ctx, req.(*AuthorizationAPINamedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APIDeletePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPINamedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APIDeletePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APIDeletePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APIDeletePolicy(ctx, req.(*AuthorizationAPINamedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APICreatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPIPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APICreatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APICreatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APICreatePolicy(ctx, req.(*AuthorizationAPIPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APIUpdatePolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPIPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APIUpdatePolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APIUpdatePolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APIUpdatePolicy(ctx, req.(*AuthorizationAPIPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APIGetRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPINamedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APIGetRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APIGetRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APIGetRole(ctx, req.(*AuthorizationAPINamedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APIDeleteRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPINamedRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APIDeleteRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APIDeleteRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APIDeleteRole(ctx, req.(*AuthorizationAPINamedRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APICreateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPIRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APICreateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APICreateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APICreateRole(ctx, req.(*AuthorizationAPIRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthorizationAPI_APIUpdateRole_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthorizationAPIRoleRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthorizationAPIServer).APIUpdateRole(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AuthorizationAPI_APIUpdateRole_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthorizationAPIServer).APIUpdateRole(ctx, req.(*AuthorizationAPIRoleRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AuthorizationAPI_ServiceDesc is the grpc.ServiceDesc for AuthorizationAPI service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AuthorizationAPI_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "service.AuthorizationAPI",
	HandlerType: (*AuthorizationAPIServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "APIGetPolicy",
			Handler:    _AuthorizationAPI_APIGetPolicy_Handler,
		},
		{
			MethodName: "APIDeletePolicy",
			Handler:    _AuthorizationAPI_APIDeletePolicy_Handler,
		},
		{
			MethodName: "APICreatePolicy",
			Handler:    _AuthorizationAPI_APICreatePolicy_Handler,
		},
		{
			MethodName: "APIUpdatePolicy",
			Handler:    _AuthorizationAPI_APIUpdatePolicy_Handler,
		},
		{
			MethodName: "APIGetRole",
			Handler:    _AuthorizationAPI_APIGetRole_Handler,
		},
		{
			MethodName: "APIDeleteRole",
			Handler:    _AuthorizationAPI_APIDeleteRole_Handler,
		},
		{
			MethodName: "APICreateRole",
			Handler:    _AuthorizationAPI_APICreateRole_Handler,
		},
		{
			MethodName: "APIUpdateRole",
			Handler:    _AuthorizationAPI_APIUpdateRole_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/sidecar/services/authorization/definition/api.proto",
}
