{{ if .Values.rbac.enabled -}}
{{ if .Values.operator.features.k8sToK8sClusterSync -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ template "kube-arangodb.rbac" . }}-k2kclustersync
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
    - apiGroups: [""]
      resources: ["pods", "services", "endpoints"]
      verbs: ["get", "update"]
    - apiGroups: [""]
      resources: ["events"]
      verbs: ["*"]
    - apiGroups: [""]
      resources: ["secrets"]
      verbs: ["get"]
    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get"]
    - apiGroups: ["database.arangodb.com"]
      resources: ["arangodeployments", "arangoclustersynchronizations"]
      verbs: ["get", "list", "watch"]

{{- end }}
{{- end }}
