{{ if .Values.rbac.enabled -}}
{{ if not (eq .Values.operator.scope "namespaced") -}}
{{ if .Values.operator.enableCRDManagement -}}

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: {{ template "kube-arangodb.rbac-cluster" . }}-crd
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get", "list", "watch", "update", "delete"]
      resourceNames:
        - "arangoclustersynchronizations.database.arangodb.com"
        - "arangotasks.database.arangodb.com"

{{- end }}
{{- end }}
{{- end }}