kind: Service
apiVersion: v1
metadata:
  name: arangodb-exposed-cluster
spec:
  selector:
    app: arangodb
    role: coordinator
  type: NodePort
  publishNotReadyAddresses: true
  ports:
    - protocol: TCP
      port: 8529
      targetPort: 8529
      nodePort: 31529
