apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "production-cluster"
spec:
  metrics:
    mode: sidecar
    enabled: true
    image: 'arangodb/arangodb-exporter:0.1.8'
    tls: false
  annotations:
    prometheus.io/scrape: 'true'
    prometheus.io/port: '9101'
    prometheus.io/scrape_interval: '5s'
  mode: Cluster
  image: 'arangodb/arangodb:3.10.6'
  environment: Production
