apiVersion: "database.arangodb.com/v1"
kind: "ArangoDeployment"
metadata:
  name: "example-simple-single"
spec:
  mode: Single
  image: 'arangodb/arangodb:3.12.2'
  gateway:
    enabled: true
  gateways:
    count: 1
---
apiVersion: "networking.arangodb.com/v1alpha1"
kind: "ArangoRoute"
metadata:
  name: "example-simple-single-route"
spec:
  deployment: example-simple-single
  destination:
    service:
      name: example-simple-single
      port: 8529
    schema: https
    tls:
      insecure: true
    path: "/_api/"
  route:
    path: "/secondary/"
