apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomlextensions.ml.arangodb.com
spec:
  group: ml.arangodb.com
  names:
    kind: ArangoMLExtension
    listKind: ArangoMLExtensionList
    plural: arangomlextensions
    singular: arangomlextension
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
