apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangomlcronjobs.ml.arangodb.com
spec:
  group: ml.arangodb.com
  names:
    kind: ArangoMLCronJob
    listKind: ArangoMLCronJobList
    plural: arangomlcronjobs
    singular: arangomlcronjob
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
