apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangopermissionroles.permission.arangodb.com
spec:
  group: permission.arangodb.com
  names:
    kind: ArangoPermissionRole
    listKind: ArangoPermissionRoleList
    plural: arangopermissionroles
    singular: arangopermissionrole
    shortNames:
      - arangorole
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: '.status.conditions[?(@.type=="Ready")].status'
          description: Defines if Role is valid
          name: Ready
          type: string
      subresources:
        status: {}
