v1:
  openAPIV3Schema:
    properties:
      spec:
        properties:
          cancellation:
            description: Cancellation describes what to do during cancellation process.
            properties:
              ensureInSync:
                description: |-
                  EnsureInSync if it is true then during cancellation process data consistency is required.
                  Default value is true.
                type: boolean
              sourceReadOnly:
                description: |-
                  SourceReadOnly if it true then after cancellation source data center should be in read-only mode.
                  Default value is false.
                type: boolean
            type: object
          destination:
            properties:
              auth:
                description: Authentication holds settings needed to authentication at the syncmaster.
                properties:
                  keyfileSecretName:
                    description: |-
                      KeyfileSecretName holds the name of a Secret containing a client authentication
                      certificate formatted at keyfile in a `tls.keyfile` field.
                      If `userSecretName` has not been set,
                      the client authentication certificate found in the secret with this name is also used to configure
                      the synchronization and fetch the synchronization status.
                    type: string
                  userSecretName:
                    description: |-
                      UserSecretName holds the name of a Secret containing a `username` & `password`
                      field used for basic authentication.
                      The user identified by the username must have write access in the `_system` database
                      of the ArangoDB cluster at the endpoint.
                    type: string
                type: object
              deploymentName:
                description: |-
                  DeploymentName holds the name of an ArangoDeployment resource.
                  If set, this provides default values for masterEndpoint, auth & tls.
                type: string
              masterEndpoint:
                description: |-
                  MasterEndpoint holds a list of URLs used to reach the syncmaster(s)
                  Use this setting if the source cluster is not running inside a Kubernetes cluster
                  that is reachable from the Kubernetes cluster the `ArangoDeploymentReplication` resource is deployed in.
                  Specifying this setting and `deploymentName` at the same time is not allowed.
                items:
                  type: string
                type: array
              tls:
                description: TLS holds settings needed to verify the TLS connection to the syncmaster.
                properties:
                  caSecretName:
                    description: |-
                      CASecretName holds the name of a Secret containing a ca.crt public key for TLS validation.
                      This setting is required, unless `deploymentName` has been set.
                    type: string
                type: object
            type: object
          source:
            properties:
              auth:
                description: Authentication holds settings needed to authentication at the syncmaster.
                properties:
                  keyfileSecretName:
                    description: |-
                      KeyfileSecretName holds the name of a Secret containing a client authentication
                      certificate formatted at keyfile in a `tls.keyfile` field.
                      If `userSecretName` has not been set,
                      the client authentication certificate found in the secret with this name is also used to configure
                      the synchronization and fetch the synchronization status.
                    type: string
                  userSecretName:
                    description: |-
                      UserSecretName holds the name of a Secret containing a `username` & `password`
                      field used for basic authentication.
                      The user identified by the username must have write access in the `_system` database
                      of the ArangoDB cluster at the endpoint.
                    type: string
                type: object
              deploymentName:
                description: |-
                  DeploymentName holds the name of an ArangoDeployment resource.
                  If set, this provides default values for masterEndpoint, auth & tls.
                type: string
              masterEndpoint:
                description: |-
                  MasterEndpoint holds a list of URLs used to reach the syncmaster(s)
                  Use this setting if the source cluster is not running inside a Kubernetes cluster
                  that is reachable from the Kubernetes cluster the `ArangoDeploymentReplication` resource is deployed in.
                  Specifying this setting and `deploymentName` at the same time is not allowed.
                items:
                  type: string
                type: array
              tls:
                description: TLS holds settings needed to verify the TLS connection to the syncmaster.
                properties:
                  caSecretName:
                    description: |-
                      CASecretName holds the name of a Secret containing a ca.crt public key for TLS validation.
                      This setting is required, unless `deploymentName` has been set.
                    type: string
                type: object
            type: object
        type: object
    type: object
    x-kubernetes-preserve-unknown-fields: true
v1alpha:
  openAPIV3Schema:
    properties:
      spec:
        properties:
          cancellation:
            description: Cancellation describes what to do during cancellation process.
            properties:
              ensureInSync:
                description: |-
                  EnsureInSync if it is true then during cancellation process data consistency is required.
                  Default value is true.
                type: boolean
              sourceReadOnly:
                description: |-
                  SourceReadOnly if it true then after cancellation source data center should be in read-only mode.
                  Default value is false.
                type: boolean
            type: object
          destination:
            properties:
              auth:
                description: Authentication holds settings needed to authentication at the syncmaster.
                properties:
                  keyfileSecretName:
                    description: |-
                      KeyfileSecretName holds the name of a Secret containing a client authentication
                      certificate formatted at keyfile in a `tls.keyfile` field.
                      If `userSecretName` has not been set,
                      the client authentication certificate found in the secret with this name is also used to configure
                      the synchronization and fetch the synchronization status.
                    type: string
                  userSecretName:
                    description: |-
                      UserSecretName holds the name of a Secret containing a `username` & `password`
                      field used for basic authentication.
                      The user identified by the username must have write access in the `_system` database
                      of the ArangoDB cluster at the endpoint.
                    type: string
                type: object
              deploymentName:
                description: |-
                  DeploymentName holds the name of an ArangoDeployment resource.
                  If set, this provides default values for masterEndpoint, auth & tls.
                type: string
              masterEndpoint:
                description: |-
                  MasterEndpoint holds a list of URLs used to reach the syncmaster(s)
                  Use this setting if the source cluster is not running inside a Kubernetes cluster
                  that is reachable from the Kubernetes cluster the `ArangoDeploymentReplication` resource is deployed in.
                  Specifying this setting and `deploymentName` at the same time is not allowed.
                items:
                  type: string
                type: array
              tls:
                description: TLS holds settings needed to verify the TLS connection to the syncmaster.
                properties:
                  caSecretName:
                    description: |-
                      CASecretName holds the name of a Secret containing a ca.crt public key for TLS validation.
                      This setting is required, unless `deploymentName` has been set.
                    type: string
                type: object
            type: object
          source:
            properties:
              auth:
                description: Authentication holds settings needed to authentication at the syncmaster.
                properties:
                  keyfileSecretName:
                    description: |-
                      KeyfileSecretName holds the name of a Secret containing a client authentication
                      certificate formatted at keyfile in a `tls.keyfile` field.
                      If `userSecretName` has not been set,
                      the client authentication certificate found in the secret with this name is also used to configure
                      the synchronization and fetch the synchronization status.
                    type: string
                  userSecretName:
                    description: |-
                      UserSecretName holds the name of a Secret containing a `username` & `password`
                      field used for basic authentication.
                      The user identified by the username must have write access in the `_system` database
                      of the ArangoDB cluster at the endpoint.
                    type: string
                type: object
              deploymentName:
                description: |-
                  DeploymentName holds the name of an ArangoDeployment resource.
                  If set, this provides default values for masterEndpoint, auth & tls.
                type: string
              masterEndpoint:
                description: |-
                  MasterEndpoint holds a list of URLs used to reach the syncmaster(s)
                  Use this setting if the source cluster is not running inside a Kubernetes cluster
                  that is reachable from the Kubernetes cluster the `ArangoDeploymentReplication` resource is deployed in.
                  Specifying this setting and `deploymentName` at the same time is not allowed.
                items:
                  type: string
                type: array
              tls:
                description: TLS holds settings needed to verify the TLS connection to the syncmaster.
                properties:
                  caSecretName:
                    description: |-
                      CASecretName holds the name of a Secret containing a ca.crt public key for TLS validation.
                      This setting is required, unless `deploymentName` has been set.
                    type: string
                type: object
            type: object
        type: object
    type: object
    x-kubernetes-preserve-unknown-fields: true
v2alpha1:
  openAPIV3Schema:
    properties:
      spec:
        properties:
          cancellation:
            description: Cancellation describes what to do during cancellation process.
            properties:
              ensureInSync:
                description: |-
                  EnsureInSync if it is true then during cancellation process data consistency is required.
                  Default value is true.
                type: boolean
              sourceReadOnly:
                description: |-
                  SourceReadOnly if it true then after cancellation source data center should be in read-only mode.
                  Default value is false.
                type: boolean
            type: object
          destination:
            properties:
              auth:
                description: Authentication holds settings needed to authentication at the syncmaster.
                properties:
                  keyfileSecretName:
                    description: |-
                      KeyfileSecretName holds the name of a Secret containing a client authentication
                      certificate formatted at keyfile in a `tls.keyfile` field.
                    type: string
                  userSecretName:
                    description: |-
                      UserSecretName holds the name of a Secret containing a `username` & `password`
                      field used for basic authentication.
                      The user identified by the username must have write access in the `_system` database
                      of the ArangoDB cluster at the endpoint.
                    type: string
                type: object
              deploymentName:
                description: |-
                  DeploymentName holds the name of an ArangoDeployment resource.
                  If set this provides default values for masterEndpoint, auth & tls.
                type: string
              masterEndpoint:
                description: MasterEndpoint holds a list of URLs used to reach the syncmaster(s).
                items:
                  type: string
                type: array
              tls:
                description: TLS holds settings needed to verify the TLS connection to the syncmaster.
                properties:
                  caSecretName:
                    description: CASecretName holds the name of a Secret containing a ca.crt public key for TLS validation.
                    type: string
                type: object
            type: object
          source:
            properties:
              auth:
                description: Authentication holds settings needed to authentication at the syncmaster.
                properties:
                  keyfileSecretName:
                    description: |-
                      KeyfileSecretName holds the name of a Secret containing a client authentication
                      certificate formatted at keyfile in a `tls.keyfile` field.
                    type: string
                  userSecretName:
                    description: |-
                      UserSecretName holds the name of a Secret containing a `username` & `password`
                      field used for basic authentication.
                      The user identified by the username must have write access in the `_system` database
                      of the ArangoDB cluster at the endpoint.
                    type: string
                type: object
              deploymentName:
                description: |-
                  DeploymentName holds the name of an ArangoDeployment resource.
                  If set this provides default values for masterEndpoint, auth & tls.
                type: string
              masterEndpoint:
                description: MasterEndpoint holds a list of URLs used to reach the syncmaster(s).
                items:
                  type: string
                type: array
              tls:
                description: TLS holds settings needed to verify the TLS connection to the syncmaster.
                properties:
                  caSecretName:
                    description: CASecretName holds the name of a Secret containing a ca.crt public key for TLS validation.
                    type: string
                type: object
            type: object
        type: object
    type: object
    x-kubernetes-preserve-unknown-fields: true
