apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoroutes.networking.arangodb.com
spec:
  group: networking.arangodb.com
  names:
    kind: ArangoRoute
    listKind: ArangoRouteList
    plural: arangoroutes
    singular: arangoroute
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      subresources:
        status: {}
