apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: arangoplatformservices.platform.arangodb.com
spec:
  group: platform.arangodb.com
  names:
    kind: ArangoPlatformService
    listKind: ArangoPlatformServiceList
    plural: arangoplatformservices
    singular: arangoplatformservice
  scope: Namespaced
  versions:
    - name: v1alpha1
      schema:
        openAPIV3Schema:
          type: object
          x-kubernetes-preserve-unknown-fields: true
      served: true
      storage: true
      additionalPrinterColumns:
        - jsonPath: '.status.conditions[?(@.type=="Ready")].status'
          description: Defines if Service is valid
          name: Ready
          type: string
      subresources:
        status: {}
