{{ if .Values.rbac.enabled -}}
{{- if .Values.rbac.extensions.debug }}

apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: {{ template "kube-arangodb.rbac" . }}-debug
    namespace: {{ .Release.Namespace }}
    labels:
        app.kubernetes.io/name: {{ template "kube-arangodb.name" . }}
        helm.sh/chart: {{ .Chart.Name }}-{{ .Chart.Version }}
        app.kubernetes.io/managed-by: {{ .Release.Service }}
        app.kubernetes.io/instance: {{ .Release.Name }}
        release: {{ .Release.Name }}
rules:
  - apiGroups:
# Core
    - ""
    - "apps"
    - "batch"
# Arango
    - "analytics.arangodb.com"
    - "ml.arangodb.com"
    resources: ["*"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["pods/exec"]
    verbs: ["create"]
{{- end }}
{{- end }}