//
// DISCLAIMER
//
// Copyright 2024 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.33.0
// 	protoc        v6.33.0
// source: integrations/authorization/v0/definition/definition.proto

package definition

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Action define action used for Authorization
type Action int32

const (
	// ACTION_ANY_UNSPECIFIED is used when there is no Action defined for call
	Action_ACTION_ANY_UNSPECIFIED Action = 0
	// ACTION_LIST define Action List
	Action_ACTION_LIST Action = 1
	// ACTION_GET define Action Get
	Action_ACTION_GET Action = 2
	// ACTION_CREATE define Action Create
	Action_ACTION_CREATE Action = 3
	// ACTION_DELETE define Action Delete
	Action_ACTION_DELETE Action = 4
)

// Enum value maps for Action.
var (
	Action_name = map[int32]string{
		0: "ACTION_ANY_UNSPECIFIED",
		1: "ACTION_LIST",
		2: "ACTION_GET",
		3: "ACTION_CREATE",
		4: "ACTION_DELETE",
	}
	Action_value = map[string]int32{
		"ACTION_ANY_UNSPECIFIED": 0,
		"ACTION_LIST":            1,
		"ACTION_GET":             2,
		"ACTION_CREATE":          3,
		"ACTION_DELETE":          4,
	}
)

func (x Action) Enum() *Action {
	p := new(Action)
	*p = x
	return p
}

func (x Action) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Action) Descriptor() protoreflect.EnumDescriptor {
	return file_integrations_authorization_v0_definition_definition_proto_enumTypes[0].Descriptor()
}

func (Action) Type() protoreflect.EnumType {
	return &file_integrations_authorization_v0_definition_definition_proto_enumTypes[0]
}

func (x Action) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Action.Descriptor instead.
func (Action) EnumDescriptor() ([]byte, []int) {
	return file_integrations_authorization_v0_definition_definition_proto_rawDescGZIP(), []int{0}
}

// CanRequest define Can method Request Body
type CanRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// user define the Requester User
	User string `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	// action define the Action type
	Action Action `protobuf:"varint,2,opt,name=action,proto3,enum=authorization.Action" json:"action,omitempty"`
	// api Keeps the information about API, For example training, prediction
	Api string `protobuf:"bytes,3,opt,name=api,proto3" json:"api,omitempty"`
	// version keeps the information about used API Version, optional
	Version *string `protobuf:"bytes,4,opt,name=version,proto3,oneof" json:"version,omitempty"`
	// name keeps the information about Resource name, used in Get/Create/Delete requests
	Name *string `protobuf:"bytes,5,opt,name=name,proto3,oneof" json:"name,omitempty"`
}

func (x *CanRequest) Reset() {
	*x = CanRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v0_definition_definition_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanRequest) ProtoMessage() {}

func (x *CanRequest) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v0_definition_definition_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanRequest.ProtoReflect.Descriptor instead.
func (*CanRequest) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v0_definition_definition_proto_rawDescGZIP(), []int{0}
}

func (x *CanRequest) GetUser() string {
	if x != nil {
		return x.User
	}
	return ""
}

func (x *CanRequest) GetAction() Action {
	if x != nil {
		return x.Action
	}
	return Action_ACTION_ANY_UNSPECIFIED
}

func (x *CanRequest) GetApi() string {
	if x != nil {
		return x.Api
	}
	return ""
}

func (x *CanRequest) GetVersion() string {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return ""
}

func (x *CanRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

// CanResponse define Can method Response Body
type CanResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// allowed keeps the information if request is allowed
	Allowed bool `protobuf:"varint,1,opt,name=allowed,proto3" json:"allowed,omitempty"`
	// message keeps the information about allow/deny
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CanResponse) Reset() {
	*x = CanResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_integrations_authorization_v0_definition_definition_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CanResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CanResponse) ProtoMessage() {}

func (x *CanResponse) ProtoReflect() protoreflect.Message {
	mi := &file_integrations_authorization_v0_definition_definition_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CanResponse.ProtoReflect.Descriptor instead.
func (*CanResponse) Descriptor() ([]byte, []int) {
	return file_integrations_authorization_v0_definition_definition_proto_rawDescGZIP(), []int{1}
}

func (x *CanResponse) GetAllowed() bool {
	if x != nil {
		return x.Allowed
	}
	return false
}

func (x *CanResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_integrations_authorization_v0_definition_definition_proto protoreflect.FileDescriptor

var file_integrations_authorization_v0_definition_definition_proto_rawDesc = []byte{
	0x0a, 0x39, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2f, 0x61,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76, 0x30, 0x2f,
	0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e,
	0x69, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x75, 0x74,
	0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0xae, 0x01, 0x0a, 0x0a, 0x43,
	0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x75, 0x73, 0x65,
	0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x2d, 0x0a,
	0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x15, 0x2e,
	0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x41, 0x63,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x06, 0x61, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x10, 0x0a, 0x03,
	0x61, 0x70, 0x69, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x61, 0x70, 0x69, 0x12, 0x1d,
	0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x48,
	0x00, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x88, 0x01, 0x01, 0x12, 0x17, 0x0a,
	0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x48, 0x01, 0x52, 0x04, 0x6e,
	0x61, 0x6d, 0x65, 0x88, 0x01, 0x01, 0x42, 0x0a, 0x0a, 0x08, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x42, 0x07, 0x0a, 0x05, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x41, 0x0a, 0x0b, 0x43,
	0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x6c,
	0x6c, 0x6f, 0x77, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x61, 0x6c, 0x6c,
	0x6f, 0x77, 0x65, 0x64, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x6b,
	0x0a, 0x06, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x16, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x41, 0x4e, 0x59, 0x5f, 0x55, 0x4e, 0x53, 0x50, 0x45, 0x43, 0x49, 0x46, 0x49,
	0x45, 0x44, 0x10, 0x00, 0x12, 0x0f, 0x0a, 0x0b, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f, 0x4c,
	0x49, 0x53, 0x54, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x47, 0x45, 0x54, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x54, 0x49, 0x4f, 0x4e, 0x5f,
	0x43, 0x52, 0x45, 0x41, 0x54, 0x45, 0x10, 0x03, 0x12, 0x11, 0x0a, 0x0d, 0x41, 0x43, 0x54, 0x49,
	0x4f, 0x4e, 0x5f, 0x44, 0x45, 0x4c, 0x45, 0x54, 0x45, 0x10, 0x04, 0x32, 0x51, 0x0a, 0x0f, 0x41,
	0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x56, 0x30, 0x12, 0x3e,
	0x0a, 0x03, 0x43, 0x61, 0x6e, 0x12, 0x19, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1a, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e,
	0x2e, 0x43, 0x61, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x4c,
	0x5a, 0x4a, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x61, 0x72, 0x61,
	0x6e, 0x67, 0x6f, 0x64, 0x62, 0x2f, 0x6b, 0x75, 0x62, 0x65, 0x2d, 0x61, 0x72, 0x61, 0x6e, 0x67,
	0x6f, 0x64, 0x62, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x67, 0x72, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73,
	0x2f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x76,
	0x30, 0x2f, 0x64, 0x65, 0x66, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_integrations_authorization_v0_definition_definition_proto_rawDescOnce sync.Once
	file_integrations_authorization_v0_definition_definition_proto_rawDescData = file_integrations_authorization_v0_definition_definition_proto_rawDesc
)

func file_integrations_authorization_v0_definition_definition_proto_rawDescGZIP() []byte {
	file_integrations_authorization_v0_definition_definition_proto_rawDescOnce.Do(func() {
		file_integrations_authorization_v0_definition_definition_proto_rawDescData = protoimpl.X.CompressGZIP(file_integrations_authorization_v0_definition_definition_proto_rawDescData)
	})
	return file_integrations_authorization_v0_definition_definition_proto_rawDescData
}

var file_integrations_authorization_v0_definition_definition_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_integrations_authorization_v0_definition_definition_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_integrations_authorization_v0_definition_definition_proto_goTypes = []interface{}{
	(Action)(0),         // 0: authorization.Action
	(*CanRequest)(nil),  // 1: authorization.CanRequest
	(*CanResponse)(nil), // 2: authorization.CanResponse
}
var file_integrations_authorization_v0_definition_definition_proto_depIdxs = []int32{
	0, // 0: authorization.CanRequest.action:type_name -> authorization.Action
	1, // 1: authorization.AuthorizationV0.Can:input_type -> authorization.CanRequest
	2, // 2: authorization.AuthorizationV0.Can:output_type -> authorization.CanResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_integrations_authorization_v0_definition_definition_proto_init() }
func file_integrations_authorization_v0_definition_definition_proto_init() {
	if File_integrations_authorization_v0_definition_definition_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_integrations_authorization_v0_definition_definition_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_integrations_authorization_v0_definition_definition_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CanResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	file_integrations_authorization_v0_definition_definition_proto_msgTypes[0].OneofWrappers = []interface{}{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_integrations_authorization_v0_definition_definition_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_integrations_authorization_v0_definition_definition_proto_goTypes,
		DependencyIndexes: file_integrations_authorization_v0_definition_definition_proto_depIdxs,
		EnumInfos:         file_integrations_authorization_v0_definition_definition_proto_enumTypes,
		MessageInfos:      file_integrations_authorization_v0_definition_definition_proto_msgTypes,
	}.Build()
	File_integrations_authorization_v0_definition_definition_proto = out.File
	file_integrations_authorization_v0_definition_definition_proto_rawDesc = nil
	file_integrations_authorization_v0_definition_definition_proto_goTypes = nil
	file_integrations_authorization_v0_definition_definition_proto_depIdxs = nil
}
