//go:build !ignore_autogenerated
// +build !ignore_autogenerated

//
// DISCLAIMER
//
// Copyright 2025 ArangoDB GmbH, Cologne, Germany
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
//
// Copyright holder is ArangoDB GmbH, Cologne, Germany
//

// Code generated by deepcopy-gen. DO NOT EDIT.

package authentication

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ConfigurationProviderEndpoints) DeepCopyInto(out *ConfigurationProviderEndpoints) {
	*out = *in
	if in.AuthorizationEndpoint != nil {
		in, out := &in.AuthorizationEndpoint, &out.AuthorizationEndpoint
		*out = new(string)
		**out = **in
	}
	if in.TokenEndpoint != nil {
		in, out := &in.TokenEndpoint, &out.TokenEndpoint
		*out = new(string)
		**out = **in
	}
	if in.UserInfoEndpoint != nil {
		in, out := &in.UserInfoEndpoint, &out.UserInfoEndpoint
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ConfigurationProviderEndpoints.
func (in *ConfigurationProviderEndpoints) DeepCopy() *ConfigurationProviderEndpoints {
	if in == nil {
		return nil
	}
	out := new(ConfigurationProviderEndpoints)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenID) DeepCopyInto(out *OpenID) {
	*out = *in
	in.HTTP.DeepCopyInto(&out.HTTP)
	in.Provider.DeepCopyInto(&out.Provider)
	out.Client = in.Client
	if in.Scope != nil {
		in, out := &in.Scope, &out.Scope
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.DisabledPaths != nil {
		in, out := &in.DisabledPaths, &out.DisabledPaths
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Features != nil {
		in, out := &in.Features, &out.Features
		*out = new(OpenIDFeatures)
		(*in).DeepCopyInto(*out)
	}
	if in.Claims != nil {
		in, out := &in.Claims, &out.Claims
		*out = new(OpenIDClaims)
		(*in).DeepCopyInto(*out)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenID.
func (in *OpenID) DeepCopy() *OpenID {
	if in == nil {
		return nil
	}
	out := new(OpenID)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDClaims) DeepCopyInto(out *OpenIDClaims) {
	*out = *in
	if in.Username != nil {
		in, out := &in.Username, &out.Username
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDClaims.
func (in *OpenIDClaims) DeepCopy() *OpenIDClaims {
	if in == nil {
		return nil
	}
	out := new(OpenIDClaims)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDClient) DeepCopyInto(out *OpenIDClient) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDClient.
func (in *OpenIDClient) DeepCopy() *OpenIDClient {
	if in == nil {
		return nil
	}
	out := new(OpenIDClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDFeatures) DeepCopyInto(out *OpenIDFeatures) {
	*out = *in
	if in.RefreshEnabled != nil {
		in, out := &in.RefreshEnabled, &out.RefreshEnabled
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDFeatures.
func (in *OpenIDFeatures) DeepCopy() *OpenIDFeatures {
	if in == nil {
		return nil
	}
	out := new(OpenIDFeatures)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDHTTPClient) DeepCopyInto(out *OpenIDHTTPClient) {
	*out = *in
	if in.Insecure != nil {
		in, out := &in.Insecure, &out.Insecure
		*out = new(bool)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDHTTPClient.
func (in *OpenIDHTTPClient) DeepCopy() *OpenIDHTTPClient {
	if in == nil {
		return nil
	}
	out := new(OpenIDHTTPClient)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OpenIDProvider) DeepCopyInto(out *OpenIDProvider) {
	*out = *in
	if in.ConfigurationProviderEndpoints != nil {
		in, out := &in.ConfigurationProviderEndpoints, &out.ConfigurationProviderEndpoints
		*out = new(ConfigurationProviderEndpoints)
		(*in).DeepCopyInto(*out)
	}
	if in.Issuer != nil {
		in, out := &in.Issuer, &out.Issuer
		*out = new(string)
		**out = **in
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OpenIDProvider.
func (in *OpenIDProvider) DeepCopy() *OpenIDProvider {
	if in == nil {
		return nil
	}
	out := new(OpenIDProvider)
	in.DeepCopyInto(out)
	return out
}
