---
# Source: kube-arangodb/templates/service-account.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: arango-deploymentreplication-operator
  namespace: default
  labels:
      app.kubernetes.io/name: kube-arangodb
      helm.sh/chart: kube-arangodb-1.0.3
      app.kubernetes.io/managed-by: Tiller
      app.kubernetes.io/instance: deploymentreplication
      release: deploymentreplication
---
# Source: kube-arangodb/templates/deployment-replications-operator/cluster-role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
    name: arango-deploymentreplication-operator-rbac-deployment-replication
    labels:
        app.kubernetes.io/name: kube-arangodb
        helm.sh/chart: kube-arangodb-1.0.3
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: deploymentreplication
        release: deploymentreplication
rules:
    - apiGroups: ["apiextensions.k8s.io"]
      resources: ["customresourcedefinitions"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["namespaces", "nodes"]
      verbs: ["get", "list"]
---
# Source: kube-arangodb/templates/deployment-replications-operator/cluster-role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
    name: arango-deploymentreplication-operator-rbac-deployment-replication
    labels:
        app.kubernetes.io/name: kube-arangodb
        helm.sh/chart: kube-arangodb-1.0.3
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: deploymentreplication
        release: deploymentreplication
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: ClusterRole
    name: arango-deploymentreplication-operator-rbac-deployment-replication
subjects:
    - kind: ServiceAccount
      name: arango-deploymentreplication-operator
      namespace: default
---
# Source: kube-arangodb/templates/deployment-replications-operator/role.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
    name: arango-deploymentreplication-operator-rbac-deployment-replication
    namespace: default
    labels:
        app.kubernetes.io/name: kube-arangodb
        helm.sh/chart: kube-arangodb-1.0.3
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: deploymentreplication
        release: deploymentreplication
rules:
    - apiGroups: ["replication.database.arangodb.com"]
      resources: ["arangodeploymentreplications"]
      verbs: ["*"]
    - apiGroups: ["database.arangodb.com"]
      resources: ["arangodeployments"]
      verbs: ["get"]
    - apiGroups: [""]
      resources: ["pods", "services", "endpoints", "persistentvolumeclaims", "events", "secrets"]
      verbs: ["*"]
    - apiGroups: ["apps"]
      resources: ["deployments", "replicasets"]
      verbs: ["get"]
---
# Source: kube-arangodb/templates/deployment-replications-operator/role-binding.yaml
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
    name: arango-deploymentreplication-operator-rbac-deployment-replication
    namespace: default
    labels:
        app.kubernetes.io/name: kube-arangodb
        helm.sh/chart: kube-arangodb-1.0.3
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: deploymentreplication
        release: deploymentreplication
roleRef:
    apiGroup: rbac.authorization.k8s.io
    kind: Role
    name: arango-deploymentreplication-operator-rbac-deployment-replication
subjects:
    - kind: ServiceAccount
      name: arango-deploymentreplication-operator
      namespace: default
---
# Source: kube-arangodb/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: arango-deploymentreplication-operator
  namespace: default
  labels:
    app.kubernetes.io/name: kube-arangodb
    helm.sh/chart: kube-arangodb-1.0.3
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: deploymentreplication
    release: deploymentreplication
spec:
  ports:
    - name: server
      port: 8528
      protocol: TCP
      targetPort: 8528
  selector:
    app.kubernetes.io/name: kube-arangodb
    app.kubernetes.io/managed-by: Tiller
    app.kubernetes.io/instance: deploymentreplication
    release: deploymentreplication
    role: leader
  type: ClusterIP
---
# Source: kube-arangodb/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
    name: arango-deploymentreplication-operator
    namespace: default
    labels:
        app.kubernetes.io/name: kube-arangodb
        helm.sh/chart: kube-arangodb-1.0.3
        app.kubernetes.io/managed-by: Tiller
        app.kubernetes.io/instance: deploymentreplication
        release: deploymentreplication
spec:
    replicas: 2
    strategy:
        type: Recreate
        
    selector:
        matchLabels:
            app.kubernetes.io/name: kube-arangodb
            app.kubernetes.io/managed-by: Tiller
            app.kubernetes.io/instance: deploymentreplication
            release: deploymentreplication
    template:
        metadata:
            labels:
                app.kubernetes.io/name: kube-arangodb
                helm.sh/chart: kube-arangodb-1.0.3
                app.kubernetes.io/managed-by: Tiller
                app.kubernetes.io/instance: deploymentreplication
                release: deploymentreplication
        spec:
            serviceAccountName: arango-deploymentreplication-operator
            affinity:
              nodeAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  nodeSelectorTerms:
                    - matchExpressions:
                        - key: beta.kubernetes.io/arch
                          operator: In
                          values:
                            - amd64
              podAntiAffinity:
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      topologyKey: "kubernetes.io/hostname"
                      labelSelector:
                        matchExpressions:
                          - key: app.kubernetes.io/name
                            operator: In
                            values:
                              - kube-arangodb
                          - key: app.kubernetes.io/instance
                            operator: In
                            values:
                              - deploymentreplication
            hostNetwork: false
            hostPID: false
            hostIPC: false
            securityContext:
                runAsNonRoot: true
                runAsUser: 1000
            containers:
                - name: operator
                  imagePullPolicy: Always
                  image: arangodb/kube-arangodb:1.0.3
                  args:
                    - --operator.deployment-replication

                    - --chaos.allowed=false
                  env:
                      - name: MY_POD_NAMESPACE
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.namespace
                      - name: MY_POD_NAME
                        valueFrom:
                            fieldRef:
                                fieldPath: metadata.name
                      - name: MY_POD_IP
                        valueFrom:
                            fieldRef:
                                fieldPath: status.podIP
                      - name: RELATED_IMAGE_UBI
                        value: "alpine:3.11"
                      - name: RELATED_IMAGE_METRICSEXPORTER
                        value: "arangodb/arangodb-exporter:0.1.7"
                      - name: RELATED_IMAGE_DATABASE
                        value: "arangodb/arangodb:latest"
                  ports:
                      - name: metrics
                        containerPort: 8528
                  securityContext:
                      privileged: false
                      allowPrivilegeEscalation: false
                      readOnlyRootFilesystem: true
                      capabilities:
                          drop:
                              - 'ALL'
                  livenessProbe:
                      httpGet:
                          path: /health
                          port: 8528
                          scheme: HTTPS
                      initialDelaySeconds: 5
                      periodSeconds: 10
                  readinessProbe:
                      httpGet:
                          path: /ready
                          port: 8528
                          scheme: HTTPS
                      initialDelaySeconds: 5
                      periodSeconds: 10
            tolerations:
                - key: "node.kubernetes.io/unreachable"
                  operator: "Exists"
                  effect: "NoExecute"
                  tolerationSeconds: 5
                - key: "node.kubernetes.io/not-ready"
                  operator: "Exists"
                  effect: "NoExecute"
                  tolerationSeconds: 5

---
# Source: kube-arangodb/templates/backup-operator/cluster-role-binding.yaml

---
# Source: kube-arangodb/templates/backup-operator/cluster-role.yaml

---
# Source: kube-arangodb/templates/backup-operator/role-binding.yaml

---
# Source: kube-arangodb/templates/backup-operator/role.yaml

---
# Source: kube-arangodb/templates/deployment-operator/cluster-role-binding.yaml

---
# Source: kube-arangodb/templates/deployment-operator/cluster-role.yaml

---
# Source: kube-arangodb/templates/deployment-operator/default-role-binding.yaml

---
# Source: kube-arangodb/templates/deployment-operator/default-role.yaml

---
# Source: kube-arangodb/templates/deployment-operator/role-binding.yaml

---
# Source: kube-arangodb/templates/deployment-operator/role.yaml

---
# Source: kube-arangodb/templates/storage-operator/cluster-role-binding.yaml

---
# Source: kube-arangodb/templates/storage-operator/cluster-role.yaml

---
# Source: kube-arangodb/templates/storage-operator/crd.yaml

---
# Source: kube-arangodb/templates/storage-operator/role-binding.yaml

---
# Source: kube-arangodb/templates/storage-operator/role.yaml

