{{- if eq .Values.storage.mode "azureBlobStorage" }}
{{- $abs := .Values.storage.azureBlobStorage }}
{{- $secretName := $abs.credentialsSecret | default (printf "%s-azure-credentials" .Release.Name) }}
apiVersion: platform.arangodb.com/v1beta1
kind: ArangoPlatformStorage
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  backend:
    azureBlobStorage:
      tenantID: {{ $abs.tenantID | quote }}
      accountName: {{ $abs.accountName | quote }}
      {{- with $abs.endpoint }}
      endpoint: {{ . | quote }}
      {{- end }}
      bucketName: {{ .Values.storage.bucketName | quote }}
      {{- with .Values.storage.bucketPath }}
      bucketPath: {{ . | quote }}
      {{- end }}
      credentialsSecret:
        name: {{ $secretName | quote }}
{{- end }}
