kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "kube-arangodb-init.name" . }}-developer-admin
subjects:
- kind: ServiceAccount
  name: {{ template "kube-arangodb-init.name" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "kube-arangodb-init.name" . }}-developer-admin
  apiGroup: rbac.authorization.k8s.io

