{
 "title": "Kube-ArangoDB",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "#Deployments",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(arangodb_operator_controller_deployments)",
     "legendFormat": "count"
    }
   ]
  },
  {
   "title": "Deployment Inspection Duration",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "arangodb_operator_deployment_inspect_deployment_duration",
     "legendFormat": "{{deployment}}"
    }
   ]
  },
  {
   "title": "Fetch deployment health [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_operator_deployment_resources_deployment_health_fetches[5m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Cleanup remove members [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_operator_deployment_resources_cleanupRemovedMembers[5m])) by (result)",
     "legendFormat": "{{result}}"
    }
   ]
  },
  {
   "title": "Pod inspections [5m]",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(arangodb_operator_deployment_resources_inspected_pods[5m]))"
    }
   ]
  },
  {
   "title": "Pod inspection Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 16 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "arangodb_operator_deployment_resources_inspect_pods_duration",
     "legendFormat": "{{pod}}, {{deployment}}"
    }
   ]
  }
 ]
}